/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Arial21_1.c                                           *
* Font:        Arial                                                 *
* Height:      21                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  21                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x1A0 (416)                                   *
* Character enabled:   0x1A1 (417)                                   *
* Character enabled:   0x1AF (431)                                   *
* Character enabled:   0x1B0 (432)                                   *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
    #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial21_1;

/* Start of unicode area <Latin Extended-B> */
GUI_CONST_STORAGE unsigned char acGUI_FontArial21_1_01A0[ 26] =   /* code 01A0, LATIN CAPITAL LETTER O WITH HORN */
{
    ___XXXXX, ____XX__,
    __XXXXXX, XX__XX__,
    _XXX____, XXX__X__,
    _XX_____, _XX__X__,
    XX______, __XXX___,
    XX______, __XX____,
    XX______, __XX____,
    XX______, __XX____,
    XX______, __XX____,
    _XX_____, _XXX____,
    _XXX____, XXX_____,
    __XXXXXX, XX______,
    ____XXXX, X_______
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial21_1_01A1[ 20] =   /* code 01A1, LATIN SMALL LETTER O WITH HORN */
{
    __XXXX__, XX______,
    _XXXXXX_, XX______,
    XXX__XX_, _X______,
    XX____XX, _X______,
    XX____XX, X_______,
    XX____XX, ________,
    XX____XX, ________,
    XXX__XXX, ________,
    _XXXXXX_, ________,
    __XXXX__, ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial21_1_01AF[ 26] =   /* code 01AF, LATIN CAPITAL LETTER U WITH HORN */
{
    XX______, _XX_XX__,
    XX______, _XX_XX__,
    XX______, _XX__X__,
    XX______, _XX__X__,
    XX______, _XXXX___,
    XX______, _XX_____,
    XX______, _XX_____,
    XX______, _XX_____,
    XX______, _XX_____,
    XX______, _XX_____,
    XXX_____, XXX_____,
    _XXXXXXX, XX______,
    ___XXXXX, ________
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial21_1_01B0[ 20] =   /* code 01B0, LATIN SMALL LETTER U WITH HORN */
{
    XX____XX, _XX_____,
    XX____XX, _XX_____,
    XX____XX, __X_____,
    XX____XX, __X_____,
    XX____XX, XX______,
    XX____XX, ________,
    XX____XX, ________,
    XX___XXX, ________,
    XXXXXXXX, ________,
    _XXXX_XX, ________
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontArial21_1_CharInfo[4] =
{
    {  14,  13,   1,   4,  15, acGUI_FontArial21_1_01A0 } /* code 01A0, LATIN CAPITAL LETTER O WITH HORN */
    , {  10,  10,   1,   7,  12, acGUI_FontArial21_1_01A1 } /* code 01A1, LATIN SMALL LETTER O WITH HORN */
    , {  14,  13,   1,   4,  15, acGUI_FontArial21_1_01AF } /* code 01AF, LATIN CAPITAL LETTER U WITH HORN */
    , {  11,  10,   1,   7,  12, acGUI_FontArial21_1_01B0 } /* code 01B0, LATIN SMALL LETTER U WITH HORN */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial21_1_Prop2 =
{
    0x01AF /* first character */
    , 0x01B0 /* last character  */
    , &GUI_FontArial21_1_CharInfo[  2] /* address of first character */
    , (GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial21_1_Prop1 =
{
    0x01A0 /* first character */
    , 0x01A1 /* last character  */
    , &GUI_FontArial21_1_CharInfo[  0] /* address of first character */
    , &GUI_FontArial21_1_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontArial21_1 =
{
    GUI_FONTTYPE_PROP_EXT /* type of font    */
    , 21 /* height of font  */
    , 21 /* space of font y */
    , 1 /* magnification x */
    , 1 /* magnification y */
    , {&GUI_FontArial21_1_Prop1}
    , 17 /* Baseline */
    , 10 /* Height of lowercase characters */
    , 13 /* Height of capital characters */
};

