#ifndef __GUI_TEXT_DEF__
#define __GUI_TEXT_DEF__

#include "GUI.h"
//#include "GUI_Text_Define.h"

extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial18;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial21;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial24;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial32;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial96_B_Lite;

#define _af "à"
#define _as "á"
#define _ar "ả"
#define _ax "ã"
#define _aj "ạ"
#define _aw "ă"
#define _awf "ằ"
#define _aws "ắ"
#define _awr "ẳ"
#define _awx "ẵ"
#define _awj "ặ"
#define _aa "â"
#define _aaf "ầ"
#define _aas "ấ"
#define _aar "ẩ"
#define _aax "ẫ"
#define _aaj "ậ"
#define _dd "đ"
#define _ef "è"
#define _es "é"
#define _er "ẻ"
#define _ex "ẽ"
#define _ej "ẹ"
#define _ee "ê"
#define _eef "ề"
#define _ees "ế"
#define _eer "ể"
#define _eex "ễ"
#define _eej "ệ"
#define _if "ì"
#define _is "í"
#define _ir "ỉ"
#define _ix "ĩ"
#define _ij "ị"
#define _of "ò"
#define _os "ó"
#define _or "ỏ"
#define _ox "õ"
#define _oj "ọ"
#define _oo "ô"
#define _oof "ồ"
#define _oos "ố"
#define _oor "ổ"
#define _oox "ỗ"
#define _ooj "ộ"
#define _ow "ơ"
#define _owf "ờ"
#define _ows "ớ"
#define _owr "ở"
#define _owx "ỡ"
#define _owj "ợ"
#define _uf "ù"
#define _us "ú"
#define _ur "ủ"
#define _ux "ũ"
#define _uj "ụ"
#define _uw "ư"
#define _uwf "ừ"
#define _uws "ứ"
#define _uwr "ử"
#define _uwx "ữ"
#define _uwj "ự"
#define _yf "ỳ"
#define _ys "ý"
#define _yr "ỷ"
#define _yx "ỹ"
#define _yj "ỵ"

#define _AF "À"
#define _AS "Á"
#define _AR "Ả"
#define _AX "Ã"
#define _AJ "Ạ"
#define _AW "Ă"
#define _AWF "Ằ"
#define _AWS "Ắ"
#define _AWR "Ẳ"
#define _AWX "Ẵ"
#define _AWJ "Ặ"
#define _AA "Â"
#define _AAF "Ầ"
#define _AAS "Ấ"
#define _AAR "Ẩ"
#define _AAX "Ẫ"
#define _AAJ "Ậ"
#define _DD "Đ"
#define _EF "È"
#define _ES "É"
#define _ER "Ẻ"
#define _EX "Ẽ"
#define _EJ "Ẹ"
#define _EE "Ê"
#define _EEF "Ề"
#define _EES "Ế"
#define _EER "Ể"
#define _EEX "Ễ"
#define _EEJ "Ệ"
#define _IF "Ì"
#define _IS "Í"
#define _IR "Ỉ"
#define _IX "ĩ"
#define _IJ "Ị"
#define _OF "Ò"
#define _OS "Ó"
#define _OR "Ỏ"
#define _OX "Õ"
#define _OJ "Ọ"
#define _OO "Ô"
#define _OOF "Ồ"
#define _OOS "Ố"
#define _OOR "Ổ"
#define _OOX "Ỗ"
#define _OOJ "Ộ"
#define _OW "Ơ"
#define _OWF "Ờ"
#define _OWS "Ớ"
#define _OWR "Ở"
#define _OWX "Ỡ"
#define _OWJ "Ợ"
#define _UF "Ù"
#define _US "Ú"
#define _UR "Ủ"
#define _UX "Ũ"
#define _UJ "Ụ"
#define _UW "Ư"
#define _UWF "Ừ"
#define _UWS "Ứ"
#define _UWR "Ử"
#define _UWX "Ữ"
#define _UWJ "Ự"
#define _YF "Ỳ"
#define _YR "Ỷ"
#define _YX "Ỹ"
#define _YJ "Ỵ"
#define _YS "Ý"

#define Txt_Nhap "NHẬP"
#define Txt_NhapMaBaoMat "MẬT KHẨU"
#define INFO_ENTER_FORMNAME "Nhập thông tin"
#define Txt_ThoiGian "Thời gian"
#define Txt_NgayThang "Ngày/tháng"

#define Txt_BienBan "         BIÊN BẢN       "
#define Txt_SoSerial "Số Seri:"
#define Txt_MaSoBienBan "ID-Mã in:"
#define Txt_GioIn "Thời gian:"
#define Txt_NgayIn "Ngày tháng:"
#define Txt_CheDoKiemTra "Chế độ kiểm tra:"
#define Txt_KetQua "Kết quả:"
#define Txt_BienSoXe "Biển số xe:"
#define Txt_TenLaiXe "Tên lái xe:"
#define Txt_NguoiVanHanh "Người vận hành:"
#define Txt_ChuKyNguoiVanHanh "C.ký người vận hành:"
#define Txt_ChuKyLaiXe "C.ký Lái xe:"
#define Txt_DonViCongTac "Đơn vị công tác:"
#define Txt_DiaDiem "Địa điểm:"
#define Txt_ToaDo "Tọa Độ:"
#define Txt_NguoiLamChung "Người làm chứng:"

#define WD_HOME_DOTHUDONG "ĐO THỤ ĐỘNG"
#define WD_HOME_DOCHUDONG "THỔI CHỦ ĐỘNG"
#define WD_HOME_RECORDLIST "DANH SÁCH"
#define WD_HOME_SETTING "CÀI ĐẶT"

#define Txt_DoChuDong "Đo chủ động"
#define Txt_TongCacBienBan "Tổng các biên bản:"
#define Txt_NgayHieuChinhGanNhat "Ngày hiệu chỉnh gần nhất:"

#define Txt_KhoiTaoCamBien "KHỞI TẠO CẢM BIẾN"
#define Txt_DangKhoiTaoCamBien "Đang khởi tạo cảm biến..."

#define Txt_THOI "THỔI"
#define Txt_VuiLongTHOI "\rVui lòng THỔI vào ống"
#define Txt_VuiLongTHOILai "Vui lòng THỔI lại"
#define Txt_THOICHUDONG "THỔI CHỦ ĐỘNG"
#define Txt_KetQuaKiemTra "Kết quả kiểm tra: "
#define Txt_KetQuaStringKoCo "Không có cồn trong hơi \nthở của bạn"
#define Txt_KetQuaStringCo "Có cồn trong hơi \nthở của bạn"
#define Txt_StringThuDongCo "Có nồng độ cồn \ntrong không khí"
#define Txt_StringThuDongKoCo "Không có nồng độ cồn \ntrong không khí"
#define Txt_KetQuaThuDongKoCo "KHÔNG phát hiện hơi cồn"
#define Txt_KetQuaThuDongCo "CÓ phát hiện hơi cồn"

#define Txt_DO "Đo giá trị ADC"
#define Txt_BomKhi "\rVui lòng bơm khí"
#define Txt_GiaTriADCMax "Giá trị ADC Max: "
#define Txt_GiaTriADCPeak "Giá trị ADC Peak: "
#define Txt_GiaTri90ADCMax "Giá trị 90% ADC Max: "
#define Txt_KetQuaDoADC "KẾT QUẢ ĐO ADC"

#define Txt_BT_1 "Đo"
#define Txt_BT_2 "Xả khí"

#define Txt_ThongBao "Thông báo"
#define Txt_DONGY "Đồng ý"
#define Txt_HUY "Hủy"

#define Txt_KhongLuuThongTin "Không Lưu Thông tin."
#define Txt_DangIn "Đang in..."
#define Txt_DaLuuThongTin "Đã Lưu Thông tin"
#define Txt_DangLuu "Đang lưu..."
#define Txt_Time "Đang cập nhật \nthời gian tự động.."

//#define Txt_ThoiGian            "Thời Gian"
#define Txt_BlowApSuat "Áp Suất"
#define Txt_TimeTurnOff "Tắt Máy"
#define Txt_TimeKeypad "Bàn Phím"

#define Txt_CoBan "Cơ bản"
#define Txt_HieuChinh "Hiệu chỉnh"
#define Txt_NangCao "Nâng cao"
#define WD_BT_TroVe "Trở Về"
#define WD_BT_Luu "Lưu"

#define Txt_BT_SetRecordIndex "Set Index\rOf Record"
#define Txt_BT_FullClearMem "Full Clear\rAll Record"
#define Txt_NhapIndexRecord "Nhập Index cần Set"
#define Txt_BT_DFU "DFU"

#define Txt_BT_ADC "Đo ADC"

#define Txt_BT0 "Cài đặt chung"
#define Txt_BT1 "XÓA DỮ LIỆU"
#define Txt_BT2 "TẮT TRUYỀN DL"
#define Txt_BT2_1 "BẬT TRUYỀN DL"
#define Txt_BT3 "HIỆU CHỈNH"
#define Txt_SettingHeader "CÀI ĐẶT"
#define Txt_CAIDATCHUNG "CÀI ĐẶT CHUNG"
#define Txt_HeaderHieuChinh "HIỆU CHỈNH"

#define Txt_XacNhan "Bạn muốn xóa dữ liệu \ntrong máy?"
#define Txt_SaiMK "Mật khẩu không đúng"
#define Txt_Xoaxong "Đã xóa xong dữ liệu"

#define Txt_CapNhatThanhCong "Tự động cập nhật \nthời gian thành công"
#define Txt_CapNhatKhongThanhCong "Tự động cập nhật \nthời gian không thành công"

#define Txt_SaveConfig "Lưu dữ liệu \nthành công"
#define Txt_NotSaveConfig "Lưu dữ liệu \nkhông thành công"
#define Txt_SaveCalib		"Đã lưu hiệu chỉnh"


#define Txt_CaiDatChungHeader "CÀI ĐẶT CHUNG"
#define Txt_NguoiSuDung "Người sử dụng"
#define Txt_DonVi "Đơn vị"
#define Txt_ThoiGianCDC "Thời gian \n(h:m:s)"
#define Txt_Ngay "Ngày \n(d:m:y)"
#define Txt_TatMay "Tắt máy"
#define Txt_BanPhim "Bàn phím"
#define Txt_LoiSensor "Lỗi cảm biến"
#define Txt_PinYeu "Không thể thực hiện đo \n do pin yếu"

#define Txt_DanhSachBanGhi "DANH SÁCH"

#define MTAB_CLIB_BT1 "Giá trị 1"
#define MTAB_CLIB_BT2 "Giá trị 2"
#define MTAB_CLIB_BT3 "Giá trị 3"
#define MTAB_CLIB_BT4 "Giá trị 4"
#define MTAB_CLIB_BT8 "Giá trị 5"
#define MTAB_CLIB_BT9 "Giá trị 6"
#define MTAB_CLIB_BT10 "Giá trị 7"
#define MTAB_CLIB_BT11 "Giá trị 8"
#define MTAB_CLIB_BT12 "Giá trị 9"
#define MTAB_CLIB_BT13 "Giá trị 10"
#define MTAB_CLIB_BT14 "Giá trị 11"
#define MTAB_CLIB_BT5 "Save"
#define MTAB_CLIB_BT6 "Back"
#define MTAB_CLIB_BT7 "Edit"

#endif
