/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "DataDefine.h"
#include "UserGUIService.h"
#include "AlcoholMeter.h"
#include "GUI_Text_Define.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_TEXT_4 (GUI_ID_USER + 0x05)
#define ID_TEXT_5 (GUI_ID_USER + 0x06)
#define ID_TEXT_6 (GUI_ID_USER + 0x07)
#define ID_SLIDER_0 (GUI_ID_USER + 0x08)
#define ID_SLIDER_1 (GUI_ID_USER + 0x09)
#define ID_EDIT_0 (GUI_ID_USER + 0x0A)
#define ID_EDIT_1 (GUI_ID_USER + 0x0B)
#define ID_EDIT_2 (GUI_ID_USER + 0x0C)
#define ID_EDIT_3 (GUI_ID_USER + 0x0D)
#define ID_EDIT_4 (GUI_ID_USER + 0x0E)
#define ID_EDIT_5 (GUI_ID_USER + 0x0F)
#define ID_EDIT_6 (GUI_ID_USER + 0x10)
#define ID_EDIT_7 (GUI_ID_USER + 0x11)
#define ID_TEXT_7 (GUI_ID_USER + 0x12)
#define ID_TEXT_8 (GUI_ID_USER + 0x13)
#define ID_TEXT_9 (GUI_ID_USER + 0x14)
#define ID_TEXT_10 (GUI_ID_USER + 0x15)

#define ID_IMAGE_0 (GUI_ID_USER + 0x16)
#define ID_IMAGE_1 (GUI_ID_USER + 0x17)
#define ID_IMAGE_2 (GUI_ID_USER + 0x18)

extern GUI_CONST_STORAGE GUI_BITMAP bmIconClock;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconSave;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconBack1;
extern uint32_t GetNumberFromString(uint16_t BeginAddress, char *Buffer);
// USER START (Optionally insert additional defines)
// USER END
static uint16_t ID_EDIT_FOCUS = 0;
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
    {
        {WINDOW_CreateIndirect, "", ID_WINDOW_0, 0, 20, 320, 460, 0, 0x0, 0},
        {TEXT_CreateIndirect, "Header", ID_TEXT_0, 0, 0, 320, 30, 0, 0x0, 0},
        {TEXT_CreateIndirect, "NguoiSuDung", ID_TEXT_1, 10, 51, 110, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "DonVi", ID_TEXT_2, 10, 116, 50, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "ThoiGian", ID_TEXT_3, 10, 176, 70, 36, 0, 0x0, 0},
        {TEXT_CreateIndirect, "Ngay", ID_TEXT_4, 10, 241, 55, 36, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TatMay", ID_TEXT_5, 10, 305, 55, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "BanPhim", ID_TEXT_6, 10, 354, 65, 25, 0, 0x0, 0},
        {SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 129, 301, 182, 26, 0, 0x0, 0},
        {SLIDER_CreateIndirect, "Slider", ID_SLIDER_1, 129, 350, 182, 26, 0, 0x0, 0},
        {EDIT_CreateIndirect, "nguoisudung", ID_EDIT_0, 128, 41, 183, 45, 0, 0x0, 0},
        {EDIT_CreateIndirect, "donvi", ID_EDIT_1, 128, 106, 183, 45, 0, 0x0, 0},
        {EDIT_CreateIndirect, "gio", ID_EDIT_2, 128, 171, 45, 45, 0, 0x0, 0},
        {EDIT_CreateIndirect, "phut", ID_EDIT_3, 197, 171, 45, 45, 0, 0x0, 0},
        {EDIT_CreateIndirect, "giay", ID_EDIT_4, 266, 171, 45, 45, 0, 0x0, 0},
        {TEXT_CreateIndirect, ":", ID_TEXT_7, 183, 181, 5, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, ":", ID_TEXT_8, 251, 181, 5, 25, 0, 0x0, 0},
        {EDIT_CreateIndirect, "ngay", ID_EDIT_5, 128, 236, 45, 45, 0, 0x0, 0},
        {EDIT_CreateIndirect, "thang", ID_EDIT_6, 197, 236, 45, 45, 0, 0x0, 0},
        {EDIT_CreateIndirect, "nam", ID_EDIT_7, 266, 236, 45, 45, 0, 0x0, 0},

        {TEXT_CreateIndirect, "", ID_TEXT_9, 183, 246, 5, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "", ID_TEXT_10, 251, 246, 5, 25, 0, 0x0, 0},

        {IMAGE_CreateIndirect, "BmpBack", ID_IMAGE_0, 50, 410, 42, 42, 0, 0, 0},
        {IMAGE_CreateIndirect, "BmpTimeGPS", ID_IMAGE_1, 138, 410, 42, 42, 0, 0, 0},
        {IMAGE_CreateIndirect, "BmpSave", ID_IMAGE_2, 228, 410, 42, 42, 0, 0, 0},

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id;
    char Buff[10];
    xSystem.Time = xSystem.Rtc->GetDateTime();

    if (xSystem.GLStatus.TmpTime == 0)
    {
        xSystem.TmpTime = xSystem.Time;
    }
    if (xSystem.GLStatus.TmpParam == 0)
    {
        xSystem.TmpParameters = xSystem.Parameters;
    }
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FFEFDC));

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, Txt_CaiDatChungHeader);
        TEXT_SetBkColor(hItem, GUI_MAKE_COLOR(0xFFEBC0));

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetFont(hItem, &GUI_FontArial18);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetText(hItem, Txt_NguoiSuDung);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetFont(hItem, &GUI_FontArial18);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetText(hItem, Txt_DonVi);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetFont(hItem, &GUI_FontArial18);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetText(hItem, Txt_ThoiGianCDC);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
        TEXT_SetFont(hItem, &GUI_FontArial18);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetText(hItem, Txt_Ngay);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
        TEXT_SetFont(hItem, &GUI_FontArial18);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetText(hItem, Txt_TatMay);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
        TEXT_SetFont(hItem, &GUI_FontArial18);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetText(hItem, Txt_BanPhim);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
        SLIDER_SetRange(hItem, 1, 5);
        SLIDER_SetNumTicks(hItem, 5);
        SLIDER_SetFocusColor(hItem, GUI_RED);
        SLIDER_SetWidth(hItem, 20);
        if (xSystem.GLStatus.TmpParam == 0)
        {
            SLIDER_SetValue(hItem, xSystem.Parameters.TimeAutoTurnOff);
        }
        else
        {
            SLIDER_SetValue(hItem, xSystem.TmpParameters.TimeAutoTurnOff);
        }
        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
        SLIDER_SetRange(hItem, 1, 5);
        SLIDER_SetNumTicks(hItem, 5);
        SLIDER_SetFocusColor(hItem, GUI_RED);
        SLIDER_SetWidth(hItem, 20);
        if (xSystem.GLStatus.TmpParam == 0)
        {
            SLIDER_SetValue(hItem, xSystem.Parameters.TimeoutKeypad);
        }
        else
        {
            SLIDER_SetValue(hItem, xSystem.TmpParameters.TimeoutKeypad);
        }
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
        EDIT_SetFont(hItem, &GUI_FontArial21);
        EDIT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
        if (xSystem.GLStatus.TmpParam == 0)
        {
            EDIT_SetText(hItem, (const char *)xSystem.Parameters.NguoiThucHien);
        }
        else
        {
            EDIT_SetText(hItem, (const char *)xSystem.TmpParameters.NguoiThucHien);
        }
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
        EDIT_SetFont(hItem, &GUI_FontArial21);
        EDIT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
        if (xSystem.GLStatus.TmpParam == 0)
        {
            EDIT_SetText(hItem, (const char *)xSystem.Parameters.DonVi);
        }
        else
        {
            EDIT_SetText(hItem, (const char *)xSystem.TmpParameters.DonVi);
        }

        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
        EDIT_SetFont(hItem, &GUI_FontArial21);
        EDIT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
        if (xSystem.GLStatus.TmpTime == 0)
        {
            sprintf((char *)Buff, "%02d", xSystem.Time.Hour);
        }
        else
        {
            sprintf((char *)Buff, "%02d", xSystem.TmpTime.Hour);
        }
        EDIT_SetText(hItem, (const char *)Buff);
        //EDIT_SetText(hItem, (const char *)xSystem.Record.Name.Time.Second);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
        EDIT_SetFont(hItem, &GUI_FontArial21);
        EDIT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
        if (xSystem.GLStatus.TmpTime == 0)
        {
            sprintf((char *)Buff, "%02d", xSystem.Time.Minute);
        }
        else
        {
            sprintf((char *)Buff, "%02d", xSystem.TmpTime.Minute);
        }
        EDIT_SetText(hItem, (const char *)Buff);
        //EDIT_SetText(hItem, (const char *)xSystem.Record.Name.Time.Minute);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
        EDIT_SetFont(hItem, &GUI_FontArial21);
        EDIT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
        if (xSystem.GLStatus.TmpTime == 0)
        {
            sprintf((char *)Buff, "%02d", xSystem.Time.Second);
        }
        else
        {
            sprintf((char *)Buff, "%02d", xSystem.TmpTime.Second);
        }
        EDIT_SetText(hItem, (const char *)Buff);
        //EDIT_SetText(hItem, (const uint8_t *)xSystem.Record.Name.Time.Hour);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
        EDIT_SetFont(hItem, &GUI_FontArial21);
        EDIT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
        if (xSystem.GLStatus.TmpTime == 0)
        {
            sprintf((char *)Buff, "%02d", xSystem.Time.Day);
        }
        else
        {
            sprintf((char *)Buff, "%02d", xSystem.TmpTime.Day);
        }
        EDIT_SetText(hItem, (const char *)Buff);
        //EDIT_SetText(hItem, (const char *)xSystem.Record.Name.Time.Day);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
        EDIT_SetFont(hItem, &GUI_FontArial21);
        EDIT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
        if (xSystem.GLStatus.TmpTime == 0)
        {
            sprintf((char *)Buff, "%02d", xSystem.Time.Month);
        }
        else
        {
            sprintf((char *)Buff, "%02d", xSystem.TmpTime.Month);
        }
        EDIT_SetText(hItem, (const char *)Buff);
        //EDIT_SetText(hItem, (const char *)xSystem.Record.Name.Time.Month);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
        EDIT_SetFont(hItem, &GUI_FontArial21);
        EDIT_SetTextAlign(hItem, TEXT_CF_HCENTER | TEXT_CF_VCENTER);
        if (xSystem.GLStatus.TmpTime == 0)
        {
            sprintf((char *)Buff, "%02d", xSystem.Time.Year);
        }
        else
        {
            sprintf((char *)Buff, "%02d", xSystem.TmpTime.Year);
        }
        EDIT_SetText(hItem, (const char *)Buff);
        //EDIT_SetText(hItem, (const char *)xSystem.Record.Name.Time.Year);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, ":");

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, ":");

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, ":");

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, ":");

        hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
        IMAGE_SetBitmap(hItem, &bmIconBack1);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
        IMAGE_SetBitmap(hItem, &bmIconClock);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
        IMAGE_SetBitmap(hItem, &bmIconSave);

    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_EDIT_0:
            if (NCode == WM_NOTIFICATION_CLICKED)
            {
                ID_EDIT_FOCUS = Id;
                strcpy((char *)xSystem.Keypad.Header, Txt_Nhap);
                memset(xSystem.Keypad.Str, 0, KPI_CONTENTSIZE);
                hItem = WM_GetDialogItem(pMsg->hWin, Id);
                xSystem.Keypad.StrLen = KPI_CONTENTSIZE;
                EDIT_GetText(hItem, (char *)xSystem.Keypad.Str, xSystem.Keypad.StrLen);
                xSystem.Keypad.StrLen = strlen((const char *)xSystem.Keypad.Str);
                xSystem.Keypad.WD_Req = WD_CaiDatChung;
                GUI_WD_Change(WD_KEYPAD);
            }
            break;
        case ID_EDIT_1:

            if (NCode == WM_NOTIFICATION_CLICKED)
            {
                ID_EDIT_FOCUS = Id;
                strcpy((char *)xSystem.Keypad.Header, Txt_Nhap);
                memset(xSystem.Keypad.Str, 0, KPI_CONTENTSIZE);
                hItem = WM_GetDialogItem(pMsg->hWin, Id);
                xSystem.Keypad.StrLen = KPI_CONTENTSIZE;
                EDIT_GetText(hItem, (char *)xSystem.Keypad.Str, xSystem.Keypad.StrLen);
                xSystem.Keypad.StrLen = strlen((const char *)xSystem.Keypad.Str);
                xSystem.Keypad.WD_Req = WD_CaiDatChung;
                GUI_WD_Change(WD_KEYPAD);
            }
            break;

        case ID_EDIT_2:
        case ID_EDIT_3:
        case ID_EDIT_4:
        case ID_EDIT_5:
        case ID_EDIT_6:
        case ID_EDIT_7:
            if (NCode == WM_NOTIFICATION_CLICKED)
            {
                ID_EDIT_FOCUS = Id;
                strcpy((char *)xSystem.Keypad.Header, Txt_Nhap);
                memset(xSystem.Keypad.Str, 0, KPI_CONTENTSIZE);
                hItem = WM_GetDialogItem(pMsg->hWin, Id);
                xSystem.Keypad.StrLen = KPI_CONTENTSIZE;
                EDIT_GetText(hItem, (char *)xSystem.Keypad.Str, xSystem.Keypad.StrLen);
                xSystem.Keypad.StrLen = strlen((const char *)xSystem.Keypad.Str);
                xSystem.Keypad.WD_Req = WD_CaiDatChung;
                GUI_WD_Change(WD_KEY_NUM);
            }
            break;
        case ID_SLIDER_0: // Notifications sent by 'Slider'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                xSystem.GLStatus.TmpParam = 1;
                hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
                xSystem.TmpParameters.TimeAutoTurnOff = SLIDER_GetValue(hItem);
                break;
            }
            break;

        case ID_SLIDER_1: // Notifications sent by 'Slider'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                break;
            case WM_NOTIFICATION_RELEASED:
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                xSystem.GLStatus.TmpParam = 1;
                hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
                xSystem.TmpParameters.TimeoutKeypad = SLIDER_GetValue(hItem);
                break;
            }
            break;

        case ID_IMAGE_0:
            if (NCode == WM_NOTIFICATION_CLICKED)
            {
                xSystem.GLStatus.TmpTime = 0;
                xSystem.GLStatus.TmpParam = 0;
                GUI_WD_Change(WD_SETTING);
            }
            break;
        case ID_IMAGE_1:
            if (NCode == WM_NOTIFICATION_CLICKED)
            {
                xSystem.GLStatus.TmpTime = 0;
                xSystem.GLStatus.TmpParam = 0;
                TIM_SetCounter(TIM5, 0);
                xSystem.GLStatus.SyncTimeGps = 1;
                xSystem.GLStatus.DoneSync = 0;
                DebugPrint("\rupdate time from gps\r\n");
                BTP_TimeAuto();
            }
            break;
        case ID_IMAGE_2:
            if (NCode == WM_NOTIFICATION_CLICKED)
            {
                // BTP_Next();
                xSystem.GLStatus.TmpTime = 0;
                xSystem.GLStatus.TmpParam = 0;
                BT_SaveConfig();
            }
            break;
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWD_KetQuaDoChuDong
*/
void WD_CDC_Process_Enter(void)
{
    xSystem.GLStatus.TmpParam = 1;

    if (xSystem.Keypad.Status == KP_ENTER)
    {
        switch (ID_EDIT_FOCUS)
        {
        case ID_EDIT_0:

            strcpy((char *)xSystem.Record.Name.NguoiThucHien, (const char *)xSystem.Keypad.Str);
            strcpy((char *)xSystem.TmpParameters.NguoiThucHien, (const char *)xSystem.Keypad.Str);

            break;

        case ID_EDIT_1:
            strcpy((char *)xSystem.Record.Name.DonViCongTac, (const char *)xSystem.Keypad.Str);
            strcpy((char *)xSystem.TmpParameters.DonVi, (const char *)xSystem.Keypad.Str);
            break;
        }
    }
    else if (xSystem.Keypad.Status == KP_CANCEL)
    {
    }
    GUI_WD_Change(WD_CaiDatChung);
}

void CAIDATCHUNG_Update_Fr_Keypad(void)
{
    xSystem.GLStatus.TmpTime = 1;

    WM_HWIN hItem;
    if (xSystem.Keypad.Status == KP_ENTER)
    {

        switch (ID_EDIT_FOCUS)
        {
        case ID_EDIT_2:
            xSystem.TmpTime.Hour = GetNumberFromString(0, (char *)xSystem.Keypad.Str);
            // strcpy((char *)xSystem.TmpTime.Hour, (const char *)xSystem.Keypad.Str);
            break;

        case ID_EDIT_3:
            xSystem.TmpTime.Minute = GetNumberFromString(0, (char *)xSystem.Keypad.Str);
            // strcpy((char *)xSystem.TmpTime.Minute, (const char *)xSystem.Keypad.Str);
            break;

        case ID_EDIT_4:
            xSystem.TmpTime.Second = GetNumberFromString(0, (char *)xSystem.Keypad.Str);
            // strcpy((char *)xSystem.TmpTime.Second, (const char *)xSystem.Keypad.Str);
            break;
        case ID_EDIT_5:
            xSystem.TmpTime.Day = GetNumberFromString(0, (char *)xSystem.Keypad.Str);
            // strcpy((char *)xSystem.TmpTime.Day, (const char *)xSystem.Keypad.Str);
            break;
        case ID_EDIT_6:
            xSystem.TmpTime.Month = GetNumberFromString(0, (char *)xSystem.Keypad.Str);
            // strcpy((char *)xSystem.TmpTime.Month, (const char *)xSystem.Keypad.Str);
            break;
        case ID_EDIT_7:
            xSystem.TmpTime.Year = GetNumberFromString(0, (char *)xSystem.Keypad.Str);
            // strcpy((char *)xSystem.TmpTime.Year, (const char *)xSystem.Keypad.Str);
            break;
        }
    }
    else if (xSystem.Keypad.Status == KP_CANCEL)
    {
    }
    GUI_WD_Change(WD_CaiDatChung);
}

//WM_HWIN CreateWD_KetQuaDoChuDong(void);
WM_HWIN CreateWD_CaiDatChung(void);
WM_HWIN CreateWD_CaiDatChung(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}
// USER START (Optionally insert additional public code)

// USER END

/*************************** End of file ****************************/
