/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "DataDefine.h"
#include "UserGUIService.h"
#include "AlcoholMeter.h"
#include "GUI_Text_Define.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_IMAGE_0 (GUI_ID_USER + 0x01)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x02)
#define ID_TEXT_0 (GUI_ID_USER + 0x03)
#define ID_TEXT_1 (GUI_ID_USER + 0x04)
#define ID_ICONVIEW_0 (GUI_ID_USER + 0x05)
#define ID_IMAGE_1 (GUI_ID_USER + 0x06)
#define ID_BUTTON_0 (GUI_ID_USER + 0x07)

#define ID_TEXT_2 (GUI_ID_USER + 0x08)
#define ID_TEXT_3 (GUI_ID_USER + 0x09)
#define ID_TEXT_4 (GUI_ID_USER + 0x0A)
#define ID_TEXT_5 (GUI_ID_USER + 0x0B)
#define ID_TEXT_6 (GUI_ID_USER + 0x0C)
#define ID_TEXT_7 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_1 (GUI_ID_USER + 0x0E)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

static WM_HWIN TxtHeader, TxtContent, ProgBarPercent1;
static WM_HWIN TxtHeader, TxtKQLabel, TxtKQValue, TxtKQString, TxtKQUnit;

extern GUI_CONST_STORAGE GUI_BITMAP bmALM_ICOn;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconBack1;

// USER END
extern PeakData_t peakData;
uint8_t status = 1;

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
    {
        {WINDOW_CreateIndirect, "WD_ThoiChuDong", ID_WINDOW_0, 0, 20, 320, 460, 0, 0x0, 0},
        {PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 43, 56, 235, 30, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLabel", ID_TEXT_0, 0, 0, 320, 30, 0, 0x0, 0},

        {TEXT_CreateIndirect, "TxtLabelKetQuaADCMax", ID_TEXT_2, 13, 125, 170, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtKetQuaADCMaxValue", ID_TEXT_3, 255, 125, 50, 22, 0, 0x0, 0},

        {BUTTON_CreateIndirect, "ButtonDo", ID_BUTTON_0, 117, 289, 86, 42, 0, 0x0, 0},
        {IMAGE_CreateIndirect, "IconBack", ID_IMAGE_0, 13, 410, 42, 42, 0, 0x00200020, 0},
        // USER START (Optionally insert additional widgets)
        // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'WD_ThoiChuDong'
        //
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FFEBDF));
        //
        // Initialization of 'TxtLabel'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtContent'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_TOP);
        // USER START (Optionally insert additional code for further widget initialization)

        TxtHeader = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetFont(TxtHeader, &GUI_FontArial21);
        TEXT_SetText(TxtHeader, Txt_DO);
        TEXT_SetBkColor(TxtHeader, GUI_MAKE_COLOR(0xFFEBC0));

        TxtKQLabel = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetTextAlign(TxtKQLabel, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetFont(TxtKQLabel, &GUI_FontArial21);
        TEXT_SetText(TxtKQLabel, Txt_GiaTriADCMax);
        //
        // Initialization of 'TxtKQValue'
        //
        TxtKQValue = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetTextAlign(TxtKQValue, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(TxtKQValue, &GUI_FontArial24);
        TEXT_SetTextColor(TxtKQValue, GUI_RED);
        char Buff[20];
        if (status == 1)
        {
            sprintf(Buff, "%d", peakData.peak);
            TEXT_SetText(TxtKQValue, (const char *)Buff);
        }
        else
        {
            peakData.peak = 0;
            sprintf(Buff, "%d", peakData.peak);
            TEXT_SetText(TxtKQValue, (const char *)Buff);
            status = 1;
        }
        //
        // Initialization of 'TxtKQUnit'
        //

        //
        // Initialization of 'TxtKQValue'
        //
        //
        // Initialization of 'TxtKQUnit'
        //

        //
        // Initialization of 'TxtKQValue'
        //
        TxtKQValue = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
        TEXT_SetTextAlign(TxtKQValue, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(TxtKQValue, &GUI_FontArial24);
        TEXT_SetTextColor(TxtKQValue, GUI_RED);
        char Buff2[20];
        sprintf(Buff2, "%d", peakData.max90);
        //sprintf(Buff2,"7777");
        TEXT_SetText(TxtKQValue, (const char *)Buff2);
        //
        // Initialization of 'TxtKQUnit'

        /*TxtContent = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetFont(TxtContent,&GUI_FontArial21);
        TEXT_SetText(TxtContent,Txt_BomKhi);*/

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetFont(hItem, &GUI_FontArial21);
        BUTTON_SetText(hItem, Txt_BT_1);

        ProgBarPercent1 = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
        PROGBAR_SetFont(ProgBarPercent1, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
        IMAGE_SetBitmap(hItem, &bmIconBack1);

        // USER END
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_IMAGE_0: // Notifications sent by 'IconBack'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                //BTP_Back();
                //xSystem.Keypad.WD_Req = WD_SETTING;
                GUI_WD_Change(WD_HIEUCHINH);
                // USER END
                break;
            case WM_NOTIFICATION_MOVED_OUT:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SCROLL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;

        case ID_BUTTON_0: // Notifications sent by 'ButtonDo'
            if (NCode == WM_NOTIFICATION_CLICKED)
            {
                status = 0;
                //GUI_WD_Change(WD_DOADC);
                BTP_Do();
            }
            break;
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWD_ThoiChuDong
*/
WM_HWIN CreateWD_DoADC(void);
WM_HWIN CreateWD_DoADC(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)

void DoADC_UpdatePeak(uint32_t Value)
{
    char Buff[20];
    sprintf(Buff, "%d", peakData.peak);
    TEXT_SetText(TxtKQValue, (const char *)Buff);
}

void DoADC_UpdateProgessBar(uint8_t Value)
{
    PROGBAR_SetValue(ProgBarPercent1, Value);
}

// USER END

/*************************** End of file ****************************/
