/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "DataDefine.h"
#include "UserGUIService.h"
#include "AlcoholMeter.h"
#include "GUI_Text_Define.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_ICONVIEW_0 (GUI_ID_USER + 0x02)
#define ID_ICONVIEW_1 (GUI_ID_USER + 0x03)
#define ID_ICONVIEW_2 (GUI_ID_USER + 0x08)
#define ID_ICONVIEW_3 (GUI_ID_USER + 0x09)
#define ID_TEXT_0 (GUI_ID_USER + 0x0B)
#define ID_TEXT_1 (GUI_ID_USER + 0x0C)
#define ID_TEXT_2 (GUI_ID_USER + 0x0D)
#define ID_TEXT_3 (GUI_ID_USER + 0x0E)
#define ID_TEXT_4 (GUI_ID_USER + 0x0F)
#define ID_TEXT_5 (GUI_ID_USER + 0x10)
#define ID_TEXT_6 (GUI_ID_USER + 0x11)
#define ID_TEXT_7 (GUI_ID_USER + 0x12)
#define ID_IMAGE_0 (GUI_ID_USER + 0x13)
#define ID_BUTTON_1 (GUI_ID_USER + 0x14)
#define ID_BUTTON_2 (GUI_ID_USER + 0x15)
#define ID_IMAGE_4 (GUI_ID_USER + 0x0A)
//#define  ID_HEADER_0 (GUI_ID_USER + 0x0A)

// USER START (Optionally insert additional defines)
extern System_t xSystem;

WM_HWIN TxtRecordTotal, TxtCalibDate;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_BITMAP bmIconDoChuDong;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconDoThuDong;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconCaiDat;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconDanhSachBanGhi;
extern GUI_CONST_STORAGE GUI_BITMAP bmRectangle33;
extern uint16_t GetV_Bat(void);
extern uint16_t GetPercent_Bat(void);
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
    {
        {WINDOW_CreateIndirect, "WD_Home", ID_WINDOW_0, 0, 20, 320, 460, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "BT_CaiDat", ID_BUTTON_0, 0, 0, 1, 1, 0, 0x0, 0},
        {ICONVIEW_CreateIndirect, "IconDoChuDong", ID_ICONVIEW_0, 30, 35, 110, 110, 0, 0x00640064, 0},
        {ICONVIEW_CreateIndirect, "IconDoThuDong", ID_ICONVIEW_1, 180, 35, 110, 110, 0, 0x00640064, 0},
        {ICONVIEW_CreateIndirect, "IconDanhSach", ID_ICONVIEW_2, 30, 212, 110, 110, 0, 0x00640064, 0},
        {ICONVIEW_CreateIndirect, "IconCaiDat", ID_ICONVIEW_3, 180, 212, 110, 110, 0, 0x00640064, 0},
        {TEXT_CreateIndirect, "TxtRecordList", ID_TEXT_0, 11, 405, 132, 16, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtCalibDate", ID_TEXT_1, 11, 431, 182, 16, 0, 0x0, 0},
        {TEXT_CreateIndirect, "RecordTotal", ID_TEXT_2, 262, 405, 46, 16, 0, 0x0, 0},
        {TEXT_CreateIndirect, "CalibDate", ID_TEXT_3, 224, 431, 84, 16, 0, 0x0, 0},
        {TEXT_CreateIndirect, "THOICHUDONG", ID_TEXT_4, 17, 159, 130, 18, 0, 0x0, 0},
        {TEXT_CreateIndirect, "DOTHUDONG", ID_TEXT_5, 179, 159, 114, 18, 0, 0x0, 0},
        {TEXT_CreateIndirect, "DANHSACH", ID_TEXT_6, 34, 336, 97, 18, 0, 0x0, 0},
        {TEXT_CreateIndirect, "CAIDAT", ID_TEXT_7, 204, 336, 65, 18, 0, 0x0, 0},
        //{ HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 402, 320, 68, 0, 0x0, 0 },
        //{IMAGE_CreateIndirect, "footer", ID_IMAGE_4, 0,402,320,68,0,0x0,0},

        //{IMAGE_CreateIndirect, "BackGround",ID_IMAGE_0, 0, 392, 320, 68, 0, 0, 0},

        // USER START (Optionally insert additional widgets)
        // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static uint8_t Buff[50], i;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'WD_Home'
        //
        DebugPrint("\rWM_INIT_DIALOG Home\r\n");
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00000000));
        // USER START (Optionally insert additional code for further widget initialization)
        //
        // Initialization of 'TxtRecordList'
        //
        //hItem = WM_GetDialogItem(pMsg->hWin, ID_HEADER_0);
        //HEADER_SetBkColor(hItem,GUI_MAKE_COLOR(0x1F1D1D) );
        //hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_4);
        //IMAGE_SetBitmap(hItem,&bmRectangle33 );
        //ICONVIEW_AddBitmapItem(hItem, &bmRectangle33,"");

        //ICONVIEW_SetTextColor(hItem, 1, GUI_WHITE);
        //ICONVIEW_SetFont(hItem, &GUI_FontArial18);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, Txt_TongCacBienBan);
        TEXT_SetFont(hItem, &GUI_FontArial18);
        //TEXT_SetBkColor(hItem, GUI_MAKE_COLOR(0x1F1D1D));
        //
        // Initialization of 'TxtCalibDate'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, Txt_NgayHieuChinhGanNhat);
        TEXT_SetFont(hItem, &GUI_FontArial18);
        //TEXT_SetBkColor(hItem, GUI_MAKE_COLOR(0x1F1D1D));
        //
        // Initialization of 'RecordTotal'
        //
        TxtRecordTotal = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetTextColor(TxtRecordTotal, GUI_RED);
        TEXT_SetTextAlign(TxtRecordTotal, GUI_TA_RIGHT | GUI_TA_VCENTER);
        TEXT_SetFont(TxtRecordTotal, &GUI_FontArial18);
        sprintf((char *)Buff, "%05d", RecordCount);
        TEXT_SetText(TxtRecordTotal, (const char *)Buff);
        //
        // Initialization of 'CalibDate'
        //
        TxtCalibDate = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetTextColor(TxtCalibDate, GUI_RED);
        TEXT_SetTextAlign(TxtCalibDate, GUI_TA_RIGHT | GUI_TA_VCENTER);
        TEXT_SetFont(TxtCalibDate, &GUI_FontArial18);
        TEXT_SetText(TxtCalibDate, (const char *)xSystem.Parameters.NgayHieuChinh);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_0);
        ICONVIEW_AddBitmapItem(hItem, &bmIconDoChuDong, "");
        ICONVIEW_SetTextColor(hItem, 1, GUI_WHITE);
        ICONVIEW_SetFont(hItem, &GUI_FontArial18);
        //ICONVIEW_SetBkColor(hItem, 1, GUI_BLACK);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, WD_HOME_DOCHUDONG);
        TEXT_SetFont(hItem, &GUI_FontArial18);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_1);
        ICONVIEW_AddBitmapItem(hItem, &bmIconDoThuDong, "");
        ICONVIEW_SetTextColor(hItem, 1, GUI_WHITE);
        ICONVIEW_SetFont(hItem, &GUI_FontArial18);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, WD_HOME_DOTHUDONG);
        TEXT_SetFont(hItem, &GUI_FontArial18);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_2);
        ICONVIEW_AddBitmapItem(hItem, &bmIconDanhSachBanGhi, "");
        ICONVIEW_SetTextColor(hItem, 1, GUI_WHITE);
        ICONVIEW_SetFont(hItem, &GUI_FontArial18);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, WD_HOME_RECORDLIST);
        TEXT_SetFont(hItem, &GUI_FontArial18);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_3);
        ICONVIEW_AddBitmapItem(hItem, &bmIconCaiDat, "");
        ICONVIEW_SetTextColor(hItem, 1, GUI_WHITE);
        ICONVIEW_SetFont(hItem, &GUI_FontArial18);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, WD_HOME_SETTING);
        TEXT_SetFont(hItem, &GUI_FontArial18);

        /*hItem = WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_4);
        ICONVIEW_AddBitmapItem(hItem, &bmRectangle33, "");
        ICONVIEW_SetTextColor(hItem, 1, GUI_WHITE);
        ICONVIEW_SetFont(hItem, &GUI_FontArial18);*/

        // hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
        //IMAGE_SetBitmap(hItem, &bmIcon);
        //IMAGE_SetJPEG(hItem, )
        // USER END
        DebugPrint("\rWM_INIT_DIALOG Home => end\r\n");
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_BUTTON_0: // Notifications sent by 'BT_CaiDat'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_ICONVIEW_0: // Notifications sent by 'IconDoChuDong'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                DebugPrint("\rIcon Click\r\n");
                if (GetPercent_Bat() <= 5)
                {
                    strcpy((char *)xSystem.Keypad.Header, Txt_ThongBao);
                    strcpy((char *)xSystem.Keypad.Str, Txt_PinYeu);
                    xSystem.Keypad.Status = 0;
                    xSystem.Keypad.WD_Req = WD_PINYEU;
                    GUI_WD_Change(WD_NOTIOK);
                }
                else
                {
                    xSystem.GLStatus.RequestCheckBattery = 0;
                    BTP_DoChuDong();
                }
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                DebugPrint("\rIcon Release\r\n");
                // USER END
                break;
            case WM_NOTIFICATION_MOVED_OUT:
                // USER START (Optionally insert code for reacting on notification message)
                DebugPrint("\rIcon Move\r\n");
                // USER END
                break;
            case WM_NOTIFICATION_SCROLL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                DebugPrint("\rIcon Scroll Change\r\n");
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                DebugPrint("\rIcon Select Change\r\n");
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_ICONVIEW_1: // Notifications sent by 'IconDoThuDong'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                if (GetPercent_Bat() <= 5)
                {
                    strcpy((char *)xSystem.Keypad.Header, Txt_ThongBao);
                    strcpy((char *)xSystem.Keypad.Str, Txt_PinYeu);
                    xSystem.Keypad.Status = 0;
                    xSystem.Keypad.WD_Req = WD_PINYEU;
                    GUI_WD_Change(WD_NOTIOK);
                }
                else
                {
                    xSystem.GLStatus.RequestCheckBattery = 0;
                    BTP_DoThuDong();
                }
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_MOVED_OUT:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SCROLL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_ICONVIEW_2: // Notifications sent by 'IconDanhSach'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                BTP_ListRecord();
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_MOVED_OUT:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SCROLL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_ICONVIEW_3: // Notifications sent by 'IconCaiDat'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                //MultiPage_SetPage(0);
                BTP_CaiDat();
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_MOVED_OUT:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SCROLL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWD_Home
*/
WM_HWIN CreateWD_Home(void);
WM_HWIN CreateWD_Home(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
void CreateMainMenu_Window(void)
{

    xSystem.GUI_Window[WD_MAIN_MENU] = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
}

// USER END

/*************************** End of file ****************************/
