/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "DataDefine.h"
#include "UserGUIService.h"
#include "AlcoholMeter.h"
#include "GUI_Text_Define.h"
// USER END

#include "BlowDetect.h"
#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)

#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x03)
#define ID_IMAGE_0 (GUI_ID_USER + 0x04)
#define ID_TEXT_2 (GUI_ID_USER + 0x05)
#define ID_TEXT_3 (GUI_ID_USER + 0x06)

// USER START (Optionally insert additional defines)

void WD_Header_Tick(void);
void Battery_Tick(void);

extern System_t xSystem;

WM_HWIN TxtDateID, TxtTimeID, TxtNotiID, TxtBatteryID, BmpSatID;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_BITMAP bmSAT_OK_B;
extern GUI_CONST_STORAGE GUI_BITMAP bmSAT_ERR_B;
extern GUI_CONST_STORAGE GUI_BITMAP bmSAT_DIS_B;

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
    {
        {WINDOW_CreateIndirect, "WD_Header", ID_WINDOW_0, 0, 0, 320, 20, 0, 0x0, 0},
        //{TEXT_CreateIndirect, "TxtDate", ID_TEXT_0, 10, 4, 80, 14, 0, 0x64, 0},
        {TEXT_CreateIndirect, "TxtTime", ID_TEXT_1, 6, 4, 150, 14, 0, 0x64, 0},
        {PROGBAR_CreateIndirect, "BatPercent", ID_PROGBAR_0, 290, 3, 25, 20, 0, 0x0, 0},
        {IMAGE_CreateIndirect, "BmpSAT", ID_IMAGE_0, 230, 3, 40, 20, 0, 0, 0},
        //{TEXT_CreateIndirect, "GPS", ID_TEXT_3, 220, 5, 28, 11, 0, 0x64, 0},
        {TEXT_CreateIndirect, "GPS", ID_TEXT_2, 243, 5, 45, 11, 0, 0x0, 0},
        {TEXT_CreateIndirect, "", ID_TEXT_3, 302, 2, 4, 2, 0, 0x0, 0},
        // USER START (Optionally insert additional widgets)
        // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'WD_Header'
        //
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x002F2D2D));
        // USER START (Optionally insert additional code for further widget initialization)1F1D1D
        //
        // Initialization of 'TxtDate'
        //
        /*TxtDateID = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetTextAlign(TxtDateID, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetFont(TxtDateID, &GUI_FontArial18);
        TEXT_SetTextColor(TxtDateID, GUI_MAKE_COLOR(0x00FFFFFF));
        TEXT_SetText(TxtDateID, "--/--/--"); //*/
        // Initialization of 'TxtTime'
        //
        TxtTimeID = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetTextAlign(TxtTimeID, GUI_TA_LEFT | GUI_TA_VCENTER);
        TEXT_SetFont(TxtTimeID, &GUI_FontArial18);
        TEXT_SetTextColor(TxtTimeID, GUI_MAKE_COLOR(0x00FFFFFF));
        TEXT_SetText(TxtTimeID, "--:--:--");

        TxtNotiID = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetTextAlign(TxtNotiID, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(TxtNotiID, &GUI_FontArial18);
        TEXT_SetTextColor(TxtNotiID, GUI_MAKE_COLOR(0x00FFFFFF));
        TEXT_SetText(TxtNotiID, "GPS |");

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, &GUI_FontArial18);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetText(hItem, "_");

        TxtBatteryID = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
        PROGBAR_SetBarColor(TxtBatteryID, 0, GUI_RED);
        //TxtBatteryID = PROGBAR_CreateEx(300, 2, 12, 16, 0, WM_CF_SHOW, PROGBAR_CF_VERTICAL, ID_PROGBAR_0);
        //int x0, int y0, int xSize, int ySize, WM_HWIN hParent, int WinFlags, int ExFlags, int Id

        BmpSatID = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
        IMAGE_SetBitmap(BmpSatID, &bmSAT_DIS_B);

        WD_Header_Tick();

        // USER END
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWD_Header
*/
WM_HWIN CreateWD_Header(void);
WM_HWIN CreateWD_Header(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
void CreateHeader_Window(void)
{
    xSystem.GUI_Window[WD_HEADER] = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
}

extern uint16_t GetPercent_Bat(void);
extern uint16_t GetVoltageIn(void);
extern int8_t GetTPRTTemp(void);

void WD_Header_Tick(void)
{
    char Buff[50];
    static uint8_t OldGPS = 49;

    //  if(xSystem.GUI_Manager.CurrentWindowID!=WD_MAIN_MENU) return;

    /*sprintf(Buff, "%02d/%02d/%02d", xSystem.Rtc->GetDateTime().Day, xSystem.Rtc->GetDateTime().Month, xSystem.Rtc->GetDateTime().Year);
    TEXT_SetText(TxtDateID, (const char *)Buff);*/

    sprintf(Buff, "%02d:%02d:%02d | %02d-%02d-%02d", xSystem.Rtc->GetDateTime().Hour, xSystem.Rtc->GetDateTime().Minute, xSystem.Rtc->GetDateTime().Second, xSystem.Rtc->GetDateTime().Day, xSystem.Rtc->GetDateTime().Month, xSystem.Rtc->GetDateTime().Year + 2000);
    TEXT_SetText(TxtTimeID, (const char *)Buff);

    /*if (xSystem.TimeOut.Clk1s_JumpToDFU > 0)
        sprintf(Buff, "%d", xSystem.TimeOut.Clk1s_JumpToDFU);
    else
        sprintf(Buff, "%d", GetTPRTTemp());
    TEXT_SetText(TxtNotiID, (const char *)Buff);*/

    if (OldGPS != xSystem.GPS->GetState())
    {
        if (xSystem.GPS->GetState() == GPS_ST_OK)
            IMAGE_SetBitmap(BmpSatID, &bmSAT_OK_B);
        else if (xSystem.GPS->GetState() == GPS_ST_ERR)
            IMAGE_SetBitmap(BmpSatID, &bmSAT_DIS_B);
        else
            IMAGE_SetBitmap(BmpSatID, &bmSAT_DIS_B);
        OldGPS = xSystem.GPS->GetState();
    }
    if (GetVoltageIn() > 8200)
    {
        PROGBAR_SetTextColor(TxtBatteryID, 0, GUI_RED);
        PROGBAR_SetTextColor(TxtBatteryID, 1, GUI_RED);
    }
    else
    {
        PROGBAR_SetTextColor(TxtBatteryID, 0, GUI_BLACK);
        PROGBAR_SetTextColor(TxtBatteryID, 1, GUI_BLACK);
    }
    GUI_Exec();
}
void Battery_Tick(void)
{
    PROGBAR_SetValue(TxtBatteryID, GetPercent_Bat());
    xSystem.GLStatus.RequestCheckBattery = 0;
    DebugPrint("\rUpdate battery value\r\n");
    GUI_Exec();
}

// USER END

/*************************** End of file ****************************/
