/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "DataDefine.h"
#include "UserGUIService.h"
#include "AlcoholMeter.h"
#include "GUI_Text_Define.h"
#include "GUI.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_EDIT_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_1 (GUI_ID_USER + 0x03)
#define ID_BUTTON_2 (GUI_ID_USER + 0x04)
#define ID_BUTTON_3 (GUI_ID_USER + 0x06)
#define ID_BUTTON_4 (GUI_ID_USER + 0x07)
#define ID_BUTTON_5 (GUI_ID_USER + 0x08)
#define ID_BUTTON_6 (GUI_ID_USER + 0x09)
#define ID_BUTTON_7 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_8 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_9 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_10 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_11 (GUI_ID_USER + 0x10)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

extern void MTAB_CLIB_Update_Fr_Keypad(void);
extern void Info_Enter_Update_Fr_Keypad(void);

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
    {
        {FRAMEWIN_CreateIndirect, "WD_KeyInput", ID_FRAMEWIN_0, 0, 50, 320, 410, 0, 0x0, 0},
        {EDIT_CreateIndirect, "Edit", ID_EDIT_0, 20, 10, 270, 45, 0, 0x32, 0},
        {BUTTON_CreateIndirect, "1", ID_BUTTON_0, 20, 90, 88, 50, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "3", ID_BUTTON_1, 202, 90, 88, 50, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "2", ID_BUTTON_2, 111, 90, 88, 50, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "4", ID_BUTTON_3, 20, 144, 88, 50, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "5", ID_BUTTON_4, 111, 144, 88, 50, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "6", ID_BUTTON_5, 202, 144, 88, 50, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "0", ID_BUTTON_6, 111, 252, 88, 50, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "7", ID_BUTTON_7, 20, 198, 88, 50, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "8", ID_BUTTON_8, 111, 198, 88, 50, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "9", ID_BUTTON_9, 202, 198, 88, 50, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "", ID_BUTTON_10, 202, 252, 88, 50, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "", ID_BUTTON_11, 20, 252, 88, 50, 0, 0x0, 0},
        // USER START (Optionally insert additional widgets)
        // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

WM_HWIN ID_Text_handle;

const uint8_t Key0[] = {2, '0', ' '};
const uint8_t Key1[] = {5, '1', '.', ',', '+', '-'};
const uint8_t Key2[] = {4, '2', 'A', 'B', 'C'};
const uint8_t Key3[] = {4, '3', 'D', 'E', 'F'};
const uint8_t Key4[] = {4, '4', 'G', 'H', 'I'};
const uint8_t Key5[] = {4, '5', 'J', 'K', 'L'};
const uint8_t Key6[] = {4, '6', 'M', 'N', 'O'};
const uint8_t Key7[] = {5, '7', 'P', 'Q', 'R', 'S'};
const uint8_t Key8[] = {4, '8', 'T', 'U', 'V'};
const uint8_t Key9[] = {5, '9', 'X', 'Y', 'Z', 'W'};

const uint8_t *KeyPad[] =
    {
        Key0,
        Key1,
        Key2,
        Key3,
        Key4,
        Key5,
        Key6,
        Key7,
        Key8,
        Key9,
};

uint8_t OldKey = 1;

void ProgressEnterKey(void);

void ProgressKey(char Character)
{
    static uint8_t ClkKey = 1;
    // Nhan phim > 2 lan.
    if (OldKey == Character)
    {
        if (xSystem.TimeOut.Clk100ms_KeyPad > 0)
        {
            if (ClkKey < KeyPad[Character - '0'][0])
                ClkKey++;
            else
                ClkKey = 1;
        }
        else
        {
            xSystem.Keypad.Str[xSystem.Keypad.StrLen] = KeyPad[Character - '0'][ClkKey];
            xSystem.Keypad.StrLen++;
            ClkKey = 1;
        }
    }
    else
        ClkKey = 1;
    // Key moi sau Init
    if (OldKey == 1)
    {
        xSystem.Keypad.Str[xSystem.Keypad.StrLen] = KeyPad[Character - '0'][ClkKey];
        xSystem.Keypad.StrLen++;
    }
    else if (OldKey != Character)
    {
        xSystem.Keypad.Str[xSystem.Keypad.StrLen] = KeyPad[Character - '0'][ClkKey];
        xSystem.Keypad.StrLen++;
    }
    else if (xSystem.Keypad.StrLen <= 0)
        xSystem.Keypad.Str[0] = KeyPad[Character - '0'][ClkKey];
    else
        xSystem.Keypad.Str[xSystem.Keypad.StrLen - 1] = KeyPad[Character - '0'][ClkKey];
    OldKey = Character;
    BeepKeypad();
    EDIT_SetText(ID_Text_handle, (char *)xSystem.Keypad.Str);
    xSystem.TimeOut.Clk100ms_KeyPad = xSystem.Parameters.TimeKeypad * 4;
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'WD_KeyInput'
        //
        hItem = pMsg->hWin;
        FRAMEWIN_SetFont(hItem, GUI_FONT_20_1);
        //
        // Initialization of 'Edit'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
        EDIT_SetFont(hItem, GUI_FONT_13_1);
        // USER START (Optionally insert additional code for further widget initialization)
        //
        // Initialization of 'Edit'
        //
        FRAMEWIN_SetFont(hItem, &GUI_FontArial32);
        FRAMEWIN_SetText(hItem, (const char *)xSystem.Keypad.Header);

        ID_Text_handle = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
        EDIT_SetText(ID_Text_handle, (const char *)xSystem.Keypad.Str);
        EDIT_SetFont(ID_Text_handle, &GUI_FontArial21);
        EDIT_SetTextAlign(ID_Text_handle, TEXT_CF_VCENTER);
        xSystem.Keypad.StrLen = strlen((char *)xSystem.Keypad.Str);
        //
        // Initialization of '1'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetFont(hItem, &GUI_FontArial21);
        //
        // Initialization of '3DEF'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
        BUTTON_SetFont(hItem, &GUI_FontArial21);
        //
        // Initialization of '2ABC'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
        BUTTON_SetFont(hItem, &GUI_FontArial21);
        //
        // Initialization of '<=='
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
        BUTTON_SetFont(hItem, &GUI_FontArial21);
        //
        // Initialization of '4GHI'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
        BUTTON_SetFont(hItem, &GUI_FontArial21);
        //
        // Initialization of '5KLMN'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
        BUTTON_SetFont(hItem, &GUI_FontArial21);
        //
        // Initialization of '6OPQ'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
        BUTTON_SetFont(hItem, &GUI_FontArial21);
        //
        // Initialization of 'Cancel'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
        BUTTON_SetFont(hItem, &GUI_FontArial21);
        //
        // Initialization of '7RST'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
        BUTTON_SetFont(hItem, &GUI_FontArial21);
        //
        // Initialization of '8UVXY'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
        BUTTON_SetFont(hItem, &GUI_FontArial21);
        //
        // Initialization of '9.,;:'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
        BUTTON_SetFont(hItem, &GUI_FontArial21);
        //
        // Initialization of 'Enter'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
        BUTTON_SetFont(hItem, &GUI_FontArial21);

        // USER END
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_EDIT_0: // Notifications sent by 'Edit'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                BeepKeypad();
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_0: // Notifications sent by '1'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                ProgressKey('1');
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_1: // Notifications sent by '3'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                ProgressKey('3');
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_2: // Notifications sent by '2'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                ProgressKey('2');
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_3: // Notifications sent by '4'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                ProgressKey('4');
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_4: // Notifications sent by '5'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                ProgressKey('5');
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_5: // Notifications sent by '6'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                ProgressKey('6');
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_6: // Notifications sent by '0'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                ProgressKey('0');
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_7: // Notifications sent by '7'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                ProgressKey('7');
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_8: // Notifications sent by '8'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                ProgressKey('8');
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_9: // Notifications sent by '9'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                ProgressKey('9');
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_10: // Notifications sent by ''
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                BeepKeypad();
                xSystem.Keypad.Status = KP_ENTER;
                EDIT_GetText(ID_Text_handle, (char *)xSystem.Keypad.Str, 40);
                ProgressEnterKey();
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_11: // Notifications sent by ''
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                BeepKeypad();
                if (xSystem.Keypad.StrLen > 0)
                {
                    xSystem.Keypad.Str[xSystem.Keypad.StrLen - 1] = 0;
                    xSystem.Keypad.StrLen--;
                }
                else
                {
                    xSystem.Keypad.Str[0] = 0;
                    OldKey = 1;
                }
                EDIT_SetText(ID_Text_handle, (char *)xSystem.Keypad.Str);
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWD_KeyInput
*/
WM_HWIN CreateWD_KeyInput(void);
WM_HWIN CreateWD_KeyInput(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)

static void ProgressEnterKey(void)
{
    if (xSystem.Keypad.Status == KP_CALCEL)
    {
        switch (xSystem.Keypad.ID_Req)
        {
        case WD_INFO_ENTER:
            Info_Enter_Update_Fr_Keypad();
            break;

        default:
            BTP_Back();
        }
    }
    else
        switch (xSystem.Keypad.ID_Req)
        {
        case WD_MTAB_SETUP:
            MTAB_CLIB_Update_Fr_Keypad();
            break;

        case WD_INFO_ENTER:
            Info_Enter_Update_Fr_Keypad();
            break;

        default:
            break;
        }
    xSystem.Keypad.ID_Req = 0;
}

void CreateKeyInput_Window(void)
{
    xSystem.GUI_Window[WD_KEY_INPUT] = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    OldKey = 1;
}

// USER END

/*************************** End of file ****************************/
