/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "DataDefine.h"
#include "UserGUIService.h"
#include "AlcoholMeter.h"
#include "GUI_Text_Define.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x05)
#define ID_TEXT_0 (GUI_ID_USER + 0x08)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
    {
        {FRAMEWIN_CreateIndirect, "WD_Notification", ID_FRAMEWIN_0, 0, 100, 320, 200, 0, 0x0, 0},
        {TEXT_CreateIndirect, "Txt_NotiString", ID_TEXT_0, 24, 20, 254, 65, 0, 0x0, 0},
        // USER START (Optionally insert additional widgets)
        // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    //int NCode;
    int Id;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'WD_Notification'
        //
        hItem = pMsg->hWin;
        FRAMEWIN_SetTitleHeight(hItem, 30);
        //
        // Initialization of 'Txt_NotiString'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        // USER START (Optionally insert additional code for further widget initialization)
        TEXT_SetFont(hItem, &GUI_FontArial24);
        DebugPrint("\r\nStr: %s\r\n", xSystem.Keypad.Str);
        TEXT_SetText(hItem, (const char *)xSystem.Keypad.Str);
        if (xSystem.Keypad.Status == 1)
            TEXT_SetTextColor(hItem, GUI_RED);
        else
            TEXT_SetTextColor(hItem, GUI_BLUE);

        hItem = pMsg->hWin;
        FRAMEWIN_SetText(hItem, (const char *)xSystem.Keypad.Header);
        FRAMEWIN_SetFont(hItem, &GUI_FontArial21);
        FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

        // USER END
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        //NCode = pMsg->Data.v;
        switch (Id)
        {
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWD_Notification
*/
WM_HWIN CreateWD_NotiSimple(void);
WM_HWIN CreateWD_NotiSimple(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)

// USER END

/*************************** End of file ****************************/
