/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "DataDefine.h"
#include "UserGUIService.h"
#include "AlcoholMeter.h"
#include "GUI_Text_Define.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x05)
#define ID_BUTTON_0 (GUI_ID_USER + 0x06)
//#define ID_BUTTON_1 (GUI_ID_USER + 0x07)
#define ID_TEXT_0 (GUI_ID_USER + 0x08)
#define ID_TEXT_1 (GUI_ID_USER + 0x09)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
    {
        {FRAMEWIN_CreateIndirect, "WD_Notification", ID_FRAMEWIN_0, 20, 117, 280, 175, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "BT_OK", ID_BUTTON_0, 90, 124, 100, 40, 0, 0x0, 0},
        //{BUTTON_CreateIndirect, "BT_CANCEL", ID_BUTTON_1, 20, 110, 100, 40, 0, 0x0, 0},
        {TEXT_CreateIndirect, "Txt_NotiString", ID_TEXT_0, 9, 50, 258, 65, 0, 0x0, 0},
        {TEXT_CreateIndirect, "", ID_TEXT_1, 0, 0, 280, 30, 0, 0x0, 0},
        // USER START (Optionally insert additional widgets)
        // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'WD_Notification'
        //
        hItem = pMsg->hWin;
        FRAMEWIN_SetTitleHeight(hItem, 30);
        FRAMEWIN_SetTitleHeight(hItem, 0);
        FRAMEWIN_SetBorderSize(hItem, 0);
        FRAMEWIN_SetTitleVis(hItem, 0);
        //
        // Initialization of 'Txt_NotiString'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        // USER START (Optionally insert additional code for further widget initialization)
        TEXT_SetFont(hItem, &GUI_FontArial24);
        DebugPrint("\r\nStr: %s\r\n", xSystem.Keypad.Str);
        TEXT_SetText(hItem, (const char *)xSystem.Keypad.Str);
        if (xSystem.Keypad.Status == 1)
            TEXT_SetTextColor(hItem, GUI_BLACK);
        else
            TEXT_SetTextColor(hItem, GUI_BLUE);

        //hItem = pMsg->hWin;
        //FRAMEWIN_SetText(hItem, (const char *)xSystem.Keypad.Header);
        //FRAMEWIN_SetFont(hItem, &GUI_FontArial24);
        //FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetText(hItem, (const char *)xSystem.Keypad.Header);
        TEXT_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FFEBDF));

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetFont(hItem, &GUI_FontArial24);
        BUTTON_SetText(hItem, "OK");

        // USER END
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_BUTTON_0: // Notifications sent by 'BT_OK'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                DebugPrint("\rXac nhan nhan nut ok\r\n");
                switch (xSystem.Keypad.WD_Req)
                {
                case WD_PINYEU:
                    GUI_WD_Change(WD_MAIN_MENU);
                    break;
                default:
                    xSystem.CTP.CTP_Sens = xSystem.CTP.CTP_Sens_DF;
                    GUI_WD_Change(xSystem.Keypad.WD_Req);
                    break;
                }
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;

            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWD_Notification
*/
WM_HWIN CreateWD_NOTIOK(void);
WM_HWIN CreateWD_NOTIOK(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
