/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "DataDefine.h"
#include "UserGUIService.h"
#include "AlcoholMeter.h"
#include "GUI_Text_Define.h"
#include "GUI.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_TEXT_4 (GUI_ID_USER + 0x05)
#define ID_TEXT_5 (GUI_ID_USER + 0x06)
#define ID_TEXT_6 (GUI_ID_USER + 0x07)
#define ID_TEXT_7 (GUI_ID_USER + 0x08)
#define ID_TEXT_8 (GUI_ID_USER + 0x09)
#define ID_TEXT_9 (GUI_ID_USER + 0x0A)
#define ID_TEXT_10 (GUI_ID_USER + 0x0B)
#define ID_TEXT_11 (GUI_ID_USER + 0x0C)
#define ID_TEXT_12 (GUI_ID_USER + 0x0D)
#define ID_TEXT_13 (GUI_ID_USER + 0x0E)
#define ID_TEXT_14 (GUI_ID_USER + 0x0F)
#define ID_TEXT_15 (GUI_ID_USER + 0x10)
#define ID_TEXT_16 (GUI_ID_USER + 0x11)
#define ID_TEXT_17 (GUI_ID_USER + 0x12)
#define ID_TEXT_18 (GUI_ID_USER + 0x13)
#define ID_TEXT_19 (GUI_ID_USER + 0x14)
#define ID_TEXT_20 (GUI_ID_USER + 0x15)
#define ID_TEXT_21 (GUI_ID_USER + 0x16)
#define ID_TEXT_22 (GUI_ID_USER + 0x17)
#define ID_TEXT_23 (GUI_ID_USER + 0x18)
#define ID_TEXT_24 (GUI_ID_USER + 0x19)
#define ID_TEXT_25 (GUI_ID_USER + 0x1A)
#define ID_TEXT_26 (GUI_ID_USER + 0x1B)
#define ID_IMAGE_0 (GUI_ID_USER + 0x1C)
#define ID_IMAGE_1 (GUI_ID_USER + 0x1D)
#define ID_IMAGE_2 (GUI_ID_USER + 0x1E)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

static uint16_t ID_EDIT_FOCUS = 0;
extern GUI_CONST_STORAGE GUI_BITMAP bmIconBack1;
//extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial21_B;

//Al_PrintInfo_t    AlPrtInfo;

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
    {
        {WINDOW_CreateIndirect, "WD_Report", ID_WINDOW_0, 0, 20, 320, 460, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtHeader", ID_TEXT_0, 0, 0, 320, 30, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbSerial", ID_TEXT_1, 13, 46, 160, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbNgay", ID_TEXT_2, 13, 71, 160, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbGio", ID_TEXT_3, 13, 96, 160, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbCheDoKiemTra", ID_TEXT_4, 13, 121, 160, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbKetQua", ID_TEXT_5, 13, 146, 160, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbNguoiVanHanh", ID_TEXT_6, 13, 171, 160, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbDonViCongTac", ID_TEXT_7, 13, 196, 160, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbChuKyVanHanh", ID_TEXT_8, 13, 221, 200, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbTenLaiXe", ID_TEXT_9, 13, 246, 160, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbDiaDiemKiemTra", ID_TEXT_10, 13, 271, 160, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbBienSoXe", ID_TEXT_11, 13, 296, 160, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbChuKyLaiXe", ID_TEXT_12, 13, 321, 160, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbNguoiLamChung", ID_TEXT_13, 13, 346, 160, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtLbDiaChi", ID_TEXT_14, 13, 371, 160, 25, 0, 0x0, 0},

        {TEXT_CreateIndirect, "TxtSerial", ID_TEXT_15, 140, 46, 169, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtNgay", ID_TEXT_16, 140, 71, 169, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtGio", ID_TEXT_17, 140, 96, 169, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtCheDoKiemTra", ID_TEXT_18, 140, 121, 169, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtKetQua", ID_TEXT_19, 140, 146, 169, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtNguoiVanhanh", ID_TEXT_20, 140, 171, 169, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtDonViCongTac", ID_TEXT_21, 140, 196, 169, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtTenLaiXe", ID_TEXT_22, 140, 246, 169, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtDiaDiemKiemTra", ID_TEXT_23, 140, 271, 169, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtBienSoXe", ID_TEXT_24, 140, 296, 169, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtNguoiLamChung", ID_TEXT_25, 140, 346, 169, 25, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtDiaChi", ID_TEXT_26, 140, 371, 169, 25, 0, 0x0, 0},

        {IMAGE_CreateIndirect, "BmHome", ID_IMAGE_0, 139, 411, 42, 42, 0, 0, 0},
        {IMAGE_CreateIndirect, "BmPrint", ID_IMAGE_1, 238, 411, 42, 42, 0, 0, 0},
        {IMAGE_CreateIndirect, "BmBack", ID_IMAGE_2, 40, 411, 42, 42, 0, 0, 0},
        // USER START (Optionally insert additional widgets)
        // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
void WD_RP_Process_Enter(void);
// USER END
//void Record_Store();
static int reportFrom = 0;
void setReportFrom(int from)
{
    // 0: Measure, 1: List record
    reportFrom = from;
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    // USER START (Optionally insert additional variables)
    int NCode;
    int Id;
    uint8_t Buffer[50];
    uint16_t Tmp32;
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'TxtHeader'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetBkColor(hItem, GUI_MAKE_COLOR(0xFFEBC0));
        TEXT_SetFont(hItem, &GUI_FontArial21);
        //
        // Initialization of 'TxtLbSerial'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtLbNgay'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtLbGio'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtLbCheDoKiemTra'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtLbKetQua'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtLbNguoiVanHanh'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtLbDonViCongTac'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtLbChuKyVanHanh'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtLbTenLaiXe'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtLbDiaDiemKiemTra'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtLbBienSoXe'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtLbChuKyLaiXe'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtLbNguoiLamChung'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtLbDiaChi'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
        TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtSerial'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtNgay'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtGio'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtCheDoKiemTra'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtKetQua'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtNguoiVanhanh'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_20);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtDonViCongTac'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_21);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtTenLaiXe'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_22);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtDiaDiemKiemTra'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_23);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtBienSoXe'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_24);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtNguoiLamChung'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_25);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        //
        // Initialization of 'TxtDiaChi'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_26);
        TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
        // USER START (Optionally insert additional code for further widget initialization)
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FFEBDF));

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetText(hItem, Txt_BienBan);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetText(hItem, Txt_SoSerial);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetText(hItem, Txt_NgayIn);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetText(hItem, Txt_GioIn);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
        TEXT_SetText(hItem, Txt_CheDoKiemTra);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
        TEXT_SetText(hItem, Txt_KetQua);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
        TEXT_SetText(hItem, Txt_NguoiVanHanh);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
        TEXT_SetText(hItem, Txt_DonViCongTac);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
        TEXT_SetText(hItem, Txt_ChuKyNguoiVanHanh);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
        TEXT_SetText(hItem, Txt_TenLaiXe);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
        TEXT_SetText(hItem, Txt_DiaDiem);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
        TEXT_SetText(hItem, Txt_BienSoXe);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
        TEXT_SetText(hItem, Txt_ChuKyLaiXe);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
        TEXT_SetText(hItem, Txt_NguoiLamChung);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
        TEXT_SetText(hItem, Txt_ToaDo);
        TEXT_SetFont(hItem, &GUI_FontArial21);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_20);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        if (reportFrom == 0)
        {
            strcpy((char *)xSystem.Record.Name.NguoiThucHien, (const char *)xSystem.Parameters.NguoiThucHien);
        }
        TEXT_SetText(hItem, (const char *)xSystem.Record.Name.NguoiThucHien);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_21);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        if (reportFrom == 0)
        {
            strcpy((char *)xSystem.Record.Name.DonViCongTac, (const char *)xSystem.Parameters.DonVi);
        }
        TEXT_SetText(hItem, (const char *)xSystem.Record.Name.DonViCongTac);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_22);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        TEXT_SetText(hItem, (const char *)xSystem.Record.Name.TenLaiXe);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_23);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        TEXT_SetText(hItem, (const char *)xSystem.Record.Name.DiaDiemKiemTra);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_24);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        TEXT_SetText(hItem, (const char *)xSystem.Record.Name.BienSo);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_25);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        TEXT_SetText(hItem, (const char *)xSystem.Record.Name.NguoiLamChung);

        // Fill Serial Device
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        TEXT_SetText(hItem, (const char *)xSystem.Parameters.DeviceID);
        TEXT_SetTextColor(hItem, GUI_RED);

        // Fill Date month
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        sprintf((char *)Buffer, "%02d/%02d/%02d", xSystem.Record.Name.Time.Day, xSystem.Record.Name.Time.Month, xSystem.Record.Name.Time.Year);
        TEXT_SetText(hItem, (const char *)Buffer);

        // Fill Time
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        sprintf((char *)Buffer, "%02d:%02d:%02d", xSystem.Record.Name.Time.Hour, xSystem.Record.Name.Time.Minute, xSystem.Record.Name.Time.Second);
        TEXT_SetText(hItem, (const char *)Buffer);

        // Fill Che do kiem tra
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        xSystem.Record.Name.Mode = 0;
        TEXT_SetText(hItem, Txt_DoChuDong);
        // Fill Ket Qua do
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        //      xSystem.Record.Name.KetQua.value*=10;
        //      Tmp32 = (uint32_t)(xSystem.Record.Name.KetQua.value)%1000;
        //      xSystem.Record.Name.KetQua.value = Tmp32/10;
        sprintf((char *)Buffer, "%.2f mg/L", xSystem.Record.Name.KetQua.value);
        DebugPrint("\rVal:%s\r\n", Buffer);
        TEXT_SetText(hItem, (const char *)Buffer);
        TEXT_SetTextColor(hItem, GUI_RED);
        // Fill Dia Chi - Toa Do
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_26);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        //      sprintf((char*)Buffer,"%.4f-%.4f",xSystem.Record.Name.ViDo.value,xSystem.Record.Name.KinhDo.value);
        //      DebugPrint("\rPos:%s",Buffer);
        //
        //      xSystem.Record.Name.KinhDo.value*=10000;
        //      Tmp32 = (uint32_t)(xSystem.Record.Name.KinhDo.value)%10000000;
        //      xSystem.Record.Name.KinhDo.value = Tmp32/10000;
        //      xSystem.Record.Name.ViDo.value*=10000;
        //      Tmp32 = (uint32_t)(xSystem.Record.Name.ViDo.value)%10000000;
        //      xSystem.Record.Name.ViDo.value = Tmp32/10000;
        sprintf((char *)Buffer, "%.4f-%.4f", xSystem.Record.Name.ViDo.value, xSystem.Record.Name.KinhDo.value);
        DebugPrint("\rPos:%s\r\n", Buffer);
        TEXT_SetText(hItem, (const char *)Buffer);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
        IMAGE_SetBitmap(hItem, &bmIconHome);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
        IMAGE_SetBitmap(hItem, &bmIconPrint);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
        IMAGE_SetBitmap(hItem, &bmIconBack1);

        //DebugPrint("\rRP_WD_INIT_DONE");
        // USER END
        break;
    // USER START (Optionally insert additional message handling)
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        //  memset(xSystem.Keypad.Str,0,KPI_CONTENTSIZE);
        //  xSystem.Keypad.Index=0;
        //    xSystem.Keypad.StrLen=0;
        //DebugPrint("\rWM_NOTIFY_PARENT: %d-%d",Id,NCode);
        switch (Id)
        {
        // Ten nguoi van hanh
        case ID_TEXT_20:
            if (NCode == WM_NOTIFICATION_CLICKED)
            {
                /* ID_EDIT_FOCUS = Id;
                strcpy((char *)xSystem.Keypad.Header, Txt_NguoiVanHanh);
                memset(xSystem.Keypad.Str, 0, KPI_CONTENTSIZE);
                hItem = WM_GetDialogItem(pMsg->hWin, Id);
                xSystem.Keypad.StrLen = TEXT_GetText(hItem, (char *)xSystem.Keypad.Str, KPI_CONTENTSIZE);
                xSystem.Keypad.WD_Req = WD_KQ_REPORT;
                GUI_WD_Change(WD_KEYPAD); */
            }
            break;

        // Don vi cong tac
        case ID_TEXT_21:
            if (NCode == WM_NOTIFICATION_CLICKED)
            {
                /* ID_EDIT_FOCUS = Id;
                strcpy((char *)xSystem.Keypad.Header, Txt_DonViCongTac);
                memset(xSystem.Keypad.Str, 0, KPI_CONTENTSIZE);
                hItem = WM_GetDialogItem(pMsg->hWin, Id);
                xSystem.Keypad.StrLen = TEXT_GetText(hItem, (char *)xSystem.Keypad.Str, KPI_CONTENTSIZE);
                xSystem.Keypad.WD_Req = WD_KQ_REPORT;
                GUI_WD_Change(WD_KEYPAD); */
            }
            break;

        // Ten Lai Xe
        case ID_TEXT_22:
            if (NCode == WM_NOTIFICATION_CLICKED && reportFrom == 0)
            {
                ID_EDIT_FOCUS = Id;
                strcpy((char *)xSystem.Keypad.Header, Txt_TenLaiXe);
                memset(xSystem.Keypad.Str, 0, KPI_CONTENTSIZE);
                hItem = WM_GetDialogItem(pMsg->hWin, Id);
                xSystem.Keypad.StrLen = TEXT_GetText(hItem, (char *)xSystem.Keypad.Str, KPI_CONTENTSIZE);
                xSystem.Keypad.WD_Req = WD_KQ_REPORT;
                GUI_WD_Change(WD_KEYPAD);
            }
            break;

        // Dia diem kiem tra
        case ID_TEXT_23:
            if (NCode == WM_NOTIFICATION_CLICKED && reportFrom == 0)
            {
                ID_EDIT_FOCUS = Id;
                strcpy((char *)xSystem.Keypad.Header, Txt_DiaDiem);
                memset(xSystem.Keypad.Str, 0, KPI_CONTENTSIZE);
                hItem = WM_GetDialogItem(pMsg->hWin, Id);
                xSystem.Keypad.StrLen = TEXT_GetText(hItem, (char *)xSystem.Keypad.Str, KPI_CONTENTSIZE);
                xSystem.Keypad.WD_Req = WD_KQ_REPORT;
                GUI_WD_Change(WD_KEYPAD);
            }
            break;

        // Bien So Xe
        case ID_TEXT_24:
            if (NCode == WM_NOTIFICATION_CLICKED && reportFrom == 0)
            {
                ID_EDIT_FOCUS = Id;
                strcpy((char *)xSystem.Keypad.Header, Txt_BienSoXe);
                memset(xSystem.Keypad.Str, 0, KPI_CONTENTSIZE);
                hItem = WM_GetDialogItem(pMsg->hWin, Id);
                xSystem.Keypad.StrLen = TEXT_GetText(hItem, (char *)xSystem.Keypad.Str, KPI_CONTENTSIZE);
                xSystem.Keypad.WD_Req = WD_KQ_REPORT;
                GUI_WD_Change(WD_KEYPAD);
            }
            break;

        // Nguoi Lam Chung
        case ID_TEXT_25:
            if (NCode == WM_NOTIFICATION_CLICKED && reportFrom == 0)
            {
                ID_EDIT_FOCUS = Id;
                strcpy((char *)xSystem.Keypad.Header, Txt_NguoiLamChung);
                memset(xSystem.Keypad.Str, 0, KPI_CONTENTSIZE);
                hItem = WM_GetDialogItem(pMsg->hWin, Id);
                xSystem.Keypad.StrLen = TEXT_GetText(hItem, (char *)xSystem.Keypad.Str, KPI_CONTENTSIZE);
                xSystem.Keypad.WD_Req = WD_KQ_REPORT;
                GUI_WD_Change(WD_KEYPAD);
            }
            break;

        // Notifications sent by 'Home'
        case ID_IMAGE_0:
            if (NCode == WM_NOTIFICATION_CLICKED)
                BTP_Home();
            break;

        // Notifications sent by 'Print'
        case ID_IMAGE_1:
        {
            if (NCode == WM_NOTIFICATION_CLICKED)
            {
                // Not allow print if time is not sync
                //if (RTC_ReadBackupRegister(RTC_BKP_DR0) == 0x32F2)
                //{
                if (reportFrom == 0)
                {
                    DebugPrint("Store and print record %d\r\n", xSystem.Record.Name.IndexStore);
                    reportFrom = 1;
                    Record_Store();
                }
                else
                {
                    DebugPrint("Print record %d\r\n", xSystem.Record.Name.IndexStore);
                }
                BTP_Print();
                //}
            }
        }
        break;
        // Notifications sent by 'Back'
        case ID_IMAGE_2:
            if (NCode == WM_NOTIFICATION_CLICKED)
                BTP_Back();
            break;
        }
        break;
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWD_Report
*/
WM_HWIN CreateWD_Report(void);
WM_HWIN CreateWD_Report(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)

void WD_RP_Process_Enter(void)
{
    WM_HWIN hItem;
    DebugPrint("\r\nKey:%d, Type:%d, ID: %d, Str:%s\r\n", xSystem.Keypad.Status, xSystem.Keypad.Type_Req, ID_EDIT_FOCUS, xSystem.Keypad.Str);
    if (xSystem.Keypad.Status == KP_ENTER)
    {
        if (xSystem.Keypad.Type_Req == KP_REQ_PASS)
        {
            if (BTP_CheckSetupSercurity() != 0)
                MultiPage_SetPage(1);
            else
                MultiPage_SetPage(0);
        }
        else
            switch (ID_EDIT_FOCUS)
            {
                // case ID_TEXT_20:
                //     DebugPrint("\rCpy PoliName:%s\r\n", xSystem.Keypad.Str);
                //     strcpy((char *)xSystem.Record.Name.NguoiThucHien, (const char *)xSystem.Keypad.Str);
                //     break;

                /*  case ID_TEXT_21:
                DebugPrint("\rCpy DonViCongTac:%s\r\n", xSystem.Keypad.Str);
                strcpy((char *)xSystem.Record.Name.DonViCongTac, (const char *)xSystem.Keypad.Str);
                break; */

            case ID_TEXT_22:
                DebugPrint("\rCpy DrvName:%s\r\n", xSystem.Keypad.Str);
                strcpy((char *)xSystem.Record.Name.TenLaiXe, (const char *)xSystem.Keypad.Str);
                break;

            case ID_TEXT_23:
                DebugPrint("\rCpy Address:%s\r\n", xSystem.Keypad.Str);
                strcpy((char *)xSystem.Record.Name.DiaDiemKiemTra, (const char *)xSystem.Keypad.Str);
                break;

            case ID_TEXT_24:
                DebugPrint("\rCpy VehiclePlate:%s\r\n", xSystem.Keypad.Str);
                strcpy((char *)xSystem.Record.Name.BienSo, (const char *)xSystem.Keypad.Str);
                break;

            case ID_TEXT_25:
                DebugPrint("\rCpy VerifyPerson:%s\r\n", xSystem.Keypad.Str);
                strcpy((char *)xSystem.Record.Name.NguoiLamChung, (const char *)xSystem.Keypad.Str);
                break;
            }
    }
    else if (xSystem.Keypad.Status == KP_CANCEL)
    {
    }
    GUI_WD_Change(WD_KQ_REPORT);
}

// USER END

/*************************** End of file ****************************/
