/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "DataDefine.h"
#include "UserGUIService.h"
#include "AlcoholMeter.h"
#include "GUI_Text_Define.h"
#include "GUI.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_LISTVIEW_0 (GUI_ID_USER + 0x02)
#define ID_IMAGE_0 (GUI_ID_USER + 0x03)
#define ID_IMAGE_1 (GUI_ID_USER + 0x04)
#define ID_IMAGE_2 (GUI_ID_USER + 0x05)

extern GUI_CONST_STORAGE GUI_BITMAP bmIconBack1;
extern GUI_CONST_STORAGE GUI_BITMAP bmListView;

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
    {
        {WINDOW_CreateIndirect, "WD_RecordList", ID_WINDOW_0, 0, 20, 320, 460, 0, 0x0, 0},
        {TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 320, 30, 0, 0x0, 0},
        {LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 0, 30, 320, 363, 0, 0x0, 0},
        {IMAGE_CreateIndirect, "BmHome", ID_IMAGE_0, 139, 410, 42, 42, 0, 0, 0},
        {IMAGE_CreateIndirect, "BmNext", ID_IMAGE_1, 223, 410, 42, 42, 0, 0, 0},
        {IMAGE_CreateIndirect, "BmBack", ID_IMAGE_2, 54, 410, 42, 42, 0, 0, 0},
        // USER START (Optionally insert additional widgets)
        // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

extern void LISTVIEW_UpdateData(void);

const uint8_t LISTVIEW_MaxRow = 11;
char *Buff[20];
int32_t i, RowSel, ColSel;
static uint32_t IndexView = 0;
WM_HWIN ListViewID;
void setReportFrom(int from);
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'WD_RecordList'
        //
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00FFEBDF));
        //
        // Initialization of 'Text'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
        TEXT_SetFont(hItem, &GUI_FontArial24);
        //
        // Initialization of 'Listview'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
        LISTVIEW_AddColumn(hItem, 50, "STT", GUI_TA_HCENTER | GUI_TA_VCENTER);
        LISTVIEW_AddColumn(hItem, 135, Txt_ThoiGian, GUI_TA_HCENTER | GUI_TA_VCENTER);
        LISTVIEW_AddColumn(hItem, 135, Txt_NgayThang, GUI_TA_HCENTER | GUI_TA_VCENTER);
        LISTVIEW_SetGridVis(hItem, 1);
        LISTVIEW_SetHeaderHeight(hItem, 30);

        LISTVIEW_SetRowHeight(hItem, 33);
        // USER START (Optionally insert additional code for further widget initialization)
        ListViewID = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
        LISTVIEW_SetFont(ListViewID, &GUI_FontArial21);
        //LISTVIEW_SetItemBkColor(ListViewID, 1, 1,LISTVIEW_CI_SEL,GUI_MAKE_COLOR(0x000000FF));
        for (i = 0; i < LISTVIEW_MaxRow; i++)
            LISTVIEW_AddRow(ListViewID, NULL);

        if (RecordCount > 0)
        {
            IndexView = (RecordCount % 1000) - 1;
        }

        DebugPrint("\rWD_RecordList WM_INIT_DIALOG %d of %d\r\n", IndexView, RecordCount);

        LISTVIEW_UpdateData();

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetText(hItem, Txt_DanhSachBanGhi);
        TEXT_SetFont(hItem, &GUI_FontArial21);
        TEXT_SetBkColor(hItem, GUI_MAKE_COLOR(0xFFEBC0));

        hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
        IMAGE_SetBitmap(hItem, &bmIconBack1);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
        IMAGE_SetBitmap(hItem, &bmIconNext);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
        IMAGE_SetBitmap(hItem, &bmIconHome);

        // USER END
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_LISTVIEW_0: // Notifications sent by 'Listview'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                RowSel = LISTVIEW_GetSel(ListViewID);
                ColSel = LISTVIEW_GetSelCol(ListViewID);
                DebugPrint("Display record row:%d view:%d of %d\r\n", RowSel, IndexView, RecordCount);
                if ((RowSel >= 0) && (ColSel == 0 || ColSel == 1 || ColSel == 2) && RecordCount > 0 && IndexView >= RowSel)
                {
                    Record_Read(IndexView - RowSel);
                    xSystem.Keypad.WD_Req = WD_RECORDLIST;
                    DebugPrint("\rGUI_WD_Change(WD_KQ_REPORT) %d\r\n", IndexView - RowSel);
                    setReportFrom(1);
                    GUI_WD_Change(WD_KQ_REPORT);
                }
                DebugPrint("\rSel: %d,%d\r\n", RowSel, ColSel);

                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                DebugPrint("\rSel Change: %d,%d\r\n", LISTVIEW_GetSel(ListViewID), LISTVIEW_GetSelCol(ListViewID));
                //RowSel = LISTVIEW_GetSel(ListViewID);
                // USER END
                break;
            // USER START (Optionally insert additional code for further notification handling)
            case WM_NOTIFICATION_VALUE_CHANGED:
                DebugPrint("\rValue Change: %d,%d\r\n", LISTVIEW_GetSel(ListViewID), LISTVIEW_GetSelCol(ListViewID));
                break;
                // USER END
            }
            break;
        // USER START (Optionally insert additional code for further Ids)
        case ID_IMAGE_0: // Notifications sent by 'IconHome'
            if (NCode == WM_NOTIFICATION_RELEASED)
            {
                GUI_WD_Change(WD_MAIN_MENU);
            }
            break;

        case ID_IMAGE_1: // Notifications sent by 'IconNext'
            if (NCode == WM_NOTIFICATION_RELEASED)
            {
                if (IndexView > LISTVIEW_MaxRow - 1)
                    IndexView -= LISTVIEW_MaxRow - 1;
                DebugPrint("\rList Next:%d\r\n", IndexView);
                LISTVIEW_UpdateData();
            }
            break;

        case ID_IMAGE_2: // Notifications sent by 'IconBack' - Search
            if (NCode == WM_NOTIFICATION_RELEASED)
            {
                if (IndexView + LISTVIEW_MaxRow - 2 < RecordCount)
                    IndexView += LISTVIEW_MaxRow - 1;
                else
                    IndexView = RecordCount - 1;
                DebugPrint("\rList Prev:%d\r\n", IndexView);
                LISTVIEW_UpdateData();
            }
            break;
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWD_RecordList
*/
WM_HWIN CreateWD_RecordList(void);
WM_HWIN CreateWD_RecordList(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)

extern uint32_t RecordCount;
void LISTVIEW_UpdateData(void)
{
    uint8_t i = 0;
    //int32_t Index = 0;

    if (RecordCount == 0)
        return;
    //if(IndexView==-1 || IndexView>GetIndexStore()-2) {
    if (IndexView == -1)
    {
        IndexView = (RecordCount % 1000) - 1;
    }
    for (i = 0; i < LISTVIEW_MaxRow; i++)
    {
        DebugPrint("Read record %d:%d of %d:%d\r\n", i, IndexView - i, IndexView, RecordCount);
        if (IndexView >= i)
        {
            DebugPrint("Update record %d (%d) of %d\r\n", IndexView - i, i, RecordCount);
            Record_Read(IndexView - i);
            sprintf((char *)Buff, "%04d", IndexView - i + 1);
            LISTVIEW_SetItemText(ListViewID, 0, i, (const char *)Buff);

            sprintf((char *)Buff, "%02d:%02d:%02d", xSystem.Record.Name.Time.Hour, xSystem.Record.Name.Time.Minute, xSystem.Record.Name.Time.Second);
            LISTVIEW_SetItemText(ListViewID, 1, i, (const char *)Buff);

            sprintf((char *)Buff, "%02d/%02d/%02d", xSystem.Record.Name.Time.Day, xSystem.Record.Name.Time.Month, xSystem.Record.Name.Time.Year % 100);
            LISTVIEW_SetItemText(ListViewID, 2, i, (const char *)Buff);

        }
        else
        {
            //DebugPrint("Ignore record %d (%d) of %d\r\n", IndexView - i, i, RecordCount);
            LISTVIEW_SetItemText(ListViewID, 0, i, "");
            LISTVIEW_SetItemText(ListViewID, 1, i, "");
            LISTVIEW_SetItemText(ListViewID, 2, i, "");
        }
    }
}

// USER END

/*************************** End of file ****************************/
