/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "DataDefine.h"
#include "UserGUIService.h"
#include "AlcoholMeter.h"
#include "GUI_Text_Define.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_SLIDER_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_0 (GUI_ID_USER + 0x02)
#define ID_TEXT_1 (GUI_ID_USER + 0x03)
#define ID_SLIDER_1 (GUI_ID_USER + 0x04)
#define ID_TEXT_2 (GUI_ID_USER + 0x05)
#define ID_SLIDER_2 (GUI_ID_USER + 0x06)
#define ID_BUTTON_0 (GUI_ID_USER + 0x07)
#define ID_BUTTON_1 (GUI_ID_USER + 0x08)
#define ID_TEXT_3 (GUI_ID_USER + 0x09)
#define ID_SLIDER_3 (GUI_ID_USER + 0x0A)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
    {
        {FRAMEWIN_CreateIndirect, "WD_SysConfigs", ID_FRAMEWIN_0, 0, 40, 320, 440, 0, 0x0, 0},
        {SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 100, 20, 180, 35, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtBlowTime", ID_TEXT_0, 10, 30, 80, 30, 0, 0x64, 0},
        {TEXT_CreateIndirect, "TxtBlowLevel", ID_TEXT_1, 10, 80, 80, 30, 0, 0x64, 0},
        {SLIDER_CreateIndirect, "Slider", ID_SLIDER_1, 100, 70, 180, 35, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtTimeTurnOff", ID_TEXT_2, 10, 130, 80, 30, 0, 0x0, 0},
        {SLIDER_CreateIndirect, "Slider", ID_SLIDER_2, 100, 120, 180, 35, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "BT_Back", ID_BUTTON_0, 10, 360, 90, 50, 0, 0x0, 0},
        {BUTTON_CreateIndirect, "BT_Save", ID_BUTTON_1, 210, 360, 90, 50, 0, 0x0, 0},
        {TEXT_CreateIndirect, "TxtKeypadTime", ID_TEXT_3, 10, 180, 80, 30, 0, 0x0, 0},
        {SLIDER_CreateIndirect, "Slider", ID_SLIDER_3, 100, 170, 180, 35, 0, 0x0, 0},
        // USER START (Optionally insert additional widgets)
        // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int NCode;
    int Id;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'TxtBlowTime'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetText(hItem, "Blow Time");
        // USER START (Optionally insert additional code for further widget initialization)
        TEXT_SetText(hItem, Txt_BlowThoiGian);
        TEXT_SetFont(hItem, &GUI_FontArial18);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetText(hItem, Txt_BlowApSuat);
        TEXT_SetFont(hItem, &GUI_FontArial18);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetText(hItem, Txt_TimeTurnOff);
        TEXT_SetFont(hItem, &GUI_FontArial18);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetText(hItem, Txt_TimeKeypad);
        TEXT_SetFont(hItem, &GUI_FontArial18);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetText(hItem, WD_BT_TroVe);
        BUTTON_SetFont(hItem, &GUI_FontArial18);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
        BUTTON_SetText(hItem, WD_BT_Luu);
        BUTTON_SetFont(hItem, &GUI_FontArial18);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
        SLIDER_SetRange(hItem, 1, 5);
        SLIDER_SetNumTicks(hItem, 5);
        SLIDER_SetFocusColor(hItem, GUI_RED);
        SLIDER_SetWidth(hItem, 20);
        SLIDER_SetValue(hItem, xSystem.Parameters.BlowTime);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
        SLIDER_SetRange(hItem, 1, 5);
        SLIDER_SetNumTicks(hItem, 5);
        SLIDER_SetFocusColor(hItem, GUI_RED);
        SLIDER_SetWidth(hItem, 20);
        SLIDER_SetValue(hItem, xSystem.Parameters.BlowPressure);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2);
        SLIDER_SetRange(hItem, 1, 5);
        SLIDER_SetNumTicks(hItem, 5);
        SLIDER_SetFocusColor(hItem, GUI_RED);
        SLIDER_SetWidth(hItem, 20);
        SLIDER_SetValue(hItem, xSystem.Parameters.TimeAutoTurnOff);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_3);
        SLIDER_SetRange(hItem, 1, 5);
        SLIDER_SetNumTicks(hItem, 5);
        SLIDER_SetFocusColor(hItem, GUI_RED);
        SLIDER_SetWidth(hItem, 20);
        SLIDER_SetValue(hItem, xSystem.Parameters.TimeKeypad);

        // USER END
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id)
        {
        case ID_SLIDER_0: // Notifications sent by 'Slider'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
                xSystem.Parameters.BlowTime = SLIDER_GetValue(hItem);
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_SLIDER_1: // Notifications sent by 'Slider'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
                xSystem.Parameters.BlowPressure = SLIDER_GetValue(hItem);
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_SLIDER_2: // Notifications sent by 'Slider'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2);
                xSystem.Parameters.TimeAutoTurnOff = SLIDER_GetValue(hItem);
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_0: // Notifications sent by 'BT_Back'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                BTP_Back();
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_1: // Notifications sent by 'BT_Save'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                BTP_Save();
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_SLIDER_3: // Notifications sent by 'Slider'
            switch (NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_3);
                xSystem.Parameters.TimeKeypad = SLIDER_GetValue(hItem);
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
    // USER START (Optionally insert additional message handling)
    // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWD_SysConfigs
*/
WM_HWIN CreateWD_SysConfigs(void);
WM_HWIN CreateWD_SysConfigs(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)

void CreateSetup_Window(void)
{
    xSystem.GUI_Window[WD_MTAB_SETUP] = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
}

// USER END

/*************************** End of file ****************************/
